[
    {
        "type": "message",
        "user": "U1AU8DRQR",
        "text": "CI is seriously unstable",
        "ts": "1472803270.000309"
    },
    {
        "type": "message",
        "user": "U1AU8DRQR",
        "text": "what can we do with it? one has to reverify a commit million times",
        "ts": "1472803289.000310"
    },
    {
        "type": "message",
        "user": "U1AU8DRQR",
        "text": "on the other hand, is there anyone who can retrigger this for me? <https:\/\/jenkins.hyperledger.org\/job\/fabric-verify-x86_64\/820\/console>",
        "ts": "1472803399.000311"
    },
    {
        "type": "message",
        "user": "U1LES78TT",
        "text": "<@U1AU8DRQR> if you're getting `make: *** No rule to make target unit-tests.  Stop.` errors then you need to merge in the latest Makefile changes",
        "ts": "1472804478.000312"
    },
    {
        "type": "message",
        "user": "U1AU8DRQR",
        "text": "isnt that merged on master?",
        "ts": "1472804502.000313"
    },
    {
        "type": "message",
        "user": "U1LES78TT",
        "text": "yeah it's been merged into master, might not be in your branch though",
        "ts": "1472804531.000314"
    },
    {
        "type": "message",
        "user": "U1LES78TT",
        "text": "I had to do a `git pull` and update my branch before Jenkins would start",
        "ts": "1472804577.000315"
    },
    {
        "user": "U1FEUAG9E",
        "text": "<@U1FEUAG9E|harsha544> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1472812609.000316"
    },
    {
        "type": "message",
        "user": "U11HH3P7Y",
        "text": "<@U1BC5NF2S> : could you please merge this patch <https:\/\/gerrit.hyperledger.org\/r\/#\/c\/859\/>",
        "edited": {
            "user": "U11HH3P7Y",
            "ts": "1472823718.000000"
        },
        "ts": "1472823680.000317"
    },
    {
        "type": "message",
        "user": "U11HH3P7Y",
        "text": "We will re-enable this patch, after merge node-sdk changes in `convergence` and `v0.6` branches.",
        "ts": "1472823986.000319"
    },
    {
        "type": "message",
        "user": "U11HH3P7Y",
        "text": "thanks <@U1BC5NF2S>.",
        "ts": "1472832615.000320",
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "U1AU8DRQR"
                ],
                "count": 1
            }
        ]
    },
    {
        "type": "message",
        "user": "U11HH3P7Y",
        "text": "<@U0KM61BCP> <@U0KPFAZNF> <@U1AU8DRQR> : we have reverted node-sdk patch from CI.. Now, jenkins is running only go unit-tests in all branches..",
        "ts": "1472837462.000321"
    },
    {
        "type": "message",
        "user": "U11HH3P7Y",
        "text": "once `node-sdk` issues\/patch-sets fixed\/merged in all branches, we will re-enable this patch.",
        "ts": "1472837535.000322"
    },
    {
        "type": "message",
        "user": "U1AU8DRQR",
        "text": "We can I do to help in fixing? ",
        "ts": "1472837633.000323"
    },
    {
        "type": "message",
        "user": "U11HH3P7Y",
        "text": "ok sure..  you have given fix to function declaration error..",
        "ts": "1472837841.000324"
    },
    {
        "type": "message",
        "user": "U11HH3P7Y",
        "text": "I am reproducing another issues observed in `convergence` branch.. please see error @ 01:03:05.026 in <https:\/\/jenkins.hyperledger.org\/job\/fabric-verify-x86_64\/857\/console>",
        "ts": "1472837882.000325"
    },
    {
        "text": "removed an integration from this channel: <https:\/\/hyperledgerproject.slack.com\/services\/B27E40VB8|hyperledger-gerrit>",
        "bot_id": "B27E40VB8",
        "type": "message",
        "subtype": "bot_remove",
        "user": "U1BC5NF2S",
        "ts": "1472856189.000326"
    }
]