[
    {
        "type": "message",
        "user": "U1ZUSJHAA",
        "text": "<@U0YQQRNU8> Could we get the reason why transactions are invalid when we get the status of invalid transactions, not just only get a \"not found\" result?",
        "ts": "1473076242.000004"
    },
    {
        "type": "message",
        "user": "U26PBUZRT",
        "text": "Some one has found this problem with the installation's tutorial? :   In this  line:                                                    \/\/bob&gt; holding reg --name \/jars\/choc_chip --account \/account --asset \/\/mkt\/asset\/cookie \/choc_chip                                                                                                                                                                                                              , I have the following error into consola of validator:  [12:05:30 ERROR   gossip_core] unexpected error handling message of type \/mktplace.transactions.MarketPlace\/Transaction\nTraceback (most recent call last):\n  File \"\/project\/sawtooth-core\/core\/gossip\/gossip_core.py\", line 626, in _dispatcher\n    self.MessageHandlerMap[msg.MessageType][1](msg, self)\n  File \"\/project\/sawtooth-core\/core\/journal\/messages\/transaction_message.py\", line 68, in transaction_message_handler\n    journal.add_pending_transaction(msg.Transaction)\n  File \"\/project\/sawtooth-core\/core\/journal\/journal_core.py\", line 455, in add_pending_transaction\n    self.PendingTransactionBlock = self.build_transaction_block()\n  File \"\/project\/sawtooth-core\/core\/journal\/consensus\/poet\/poet_journal.py\", line 174, in build_transaction_block\n    self.TransactionStore[txnid] = txn\n  File \"\/project\/sawtooth-core\/core\/journal\/journal_core.py\", line 1272, in __setitem__\n    self._shelf[key] = value\n  File \"\/usr\/lib\/python2.7\/shelve.py\", line 132, in __setitem__\n    p.dump(value)\n  File \"\/usr\/lib\/python2.7\/copy_reg.py\", line 70, in _reduce_ex\n    raise TypeError, \"can't pickle %s objects\" % base.__name__\nTypeError: can't pickle function objects                                                                                                                                                                                                                                                -------------------------------I repeated 2 times the same process and the same result------",
        "edited": {
            "user": "U26PBUZRT",
            "ts": "1473086635.000000"
        },
        "ts": "1473078975.000005"
    },
    {
        "type": "message",
        "user": "U26PBUZRT",
        "text": "This error is throwing by commands with : choc_chip, \nSome idea?\n The first time is:  \"Next, let\u2019s create an empty cookie jar for Chocolate Chip cookies:..\"",
        "edited": {
            "user": "U26PBUZRT",
            "ts": "1473088049.000000"
        },
        "ts": "1473088002.000012"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "<@U26PBUZRT> that's a regression in the interaction between mktplace and a recent change to journal_core",
        "ts": "1473098632.000014"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "I'll start looking at a fix.",
        "ts": "1473098994.000015"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "<@U1ZUSJHAA>: \"not found\" means we don't have the transaction anymore in the validator and thus can't return a status.  we could potentially add a feature for the validator to track invalid transactions for some duration of time so it can return a better status to the client.",
        "ts": "1473099189.000016"
    },
    {
        "type": "message",
        "user": "U1XLE4K5Z",
        "text": "Can I use Sawtooth as a standalone blockchain without the need to use Fabric?",
        "edited": {
            "user": "U1XLE4K5Z",
            "ts": "1473101687.000000"
        },
        "ts": "1473101680.000017"
    },
    {
        "type": "message",
        "user": "U0N3AJSSU",
        "text": "<@U1XLE4K5Z>: yes",
        "ts": "1473101739.000019"
    },
    {
        "type": "message",
        "user": "U0N3AJSSU",
        "text": "Sawtooth is a completely separate blockchain implementation",
        "ts": "1473101757.000020"
    },
    {
        "type": "message",
        "user": "U1XLE4K5Z",
        "text": "Thanks, but it's confusing. Does this mean that Sawtooth can become the new fabric for Hyperledger?",
        "edited": {
            "user": "U1XLE4K5Z",
            "ts": "1473101964.000000"
        },
        "ts": "1473101839.000021"
    },
    {
        "type": "message",
        "user": "U0N3AJSSU",
        "text": "Yes, sawtooth and fabric are both in incubation stage",
        "ts": "1473102030.000026"
    },
    {
        "type": "message",
        "user": "U0N3AJSSU",
        "text": "And are both being actively developed",
        "ts": "1473102044.000027"
    },
    {
        "type": "message",
        "user": "U1XLE4K5Z",
        "text": "Would Sawtooth then have to be renamed to Hyperledger Fabric? Or is that name reserved for IBM?",
        "ts": "1473102176.000028"
    },
    {
        "type": "message",
        "user": "U0N3AJSSU",
        "text": "Ibm just chose the name fabric, it is a bit misleading",
        "ts": "1473102201.000029"
    },
    {
        "type": "message",
        "user": "U0N3AJSSU",
        "text": "Sawtooth was our code name, it may be renamed at some point",
        "ts": "1473102234.000030"
    },
    {
        "type": "message",
        "user": "U1XLE4K5Z",
        "text": "Ah alright I get it. So when I tell people, what the Hyperledger fabric is... I should say, it will be either Fabric or Sawtooth.",
        "edited": {
            "user": "U1XLE4K5Z",
            "ts": "1473102425.000000"
        },
        "ts": "1473102265.000031"
    },
    {
        "type": "message",
        "user": "U1XLE4K5Z",
        "text": "I'm trying to see this similar to the way we point to the Linux kernel",
        "ts": "1473102320.000032"
    },
    {
        "type": "message",
        "user": "U0VKPD6A2",
        "text": "<@U1XLE4K5Z> having a fabric was an early idea of the group, but that is not currently a goal. Instead we talk about a family of blockchain technologies. With \"fabric\" and \"sawtooth\" being two blockchain implementations. And other projects currently as related tools. More projects in blockchains and tools are expected. ",
        "ts": "1473107111.000034"
    },
    {
        "type": "message",
        "user": "U1XLE4K5Z",
        "text": "<@U0VKPD6A2> Do you foresee them both becoming fully compatible with each other on the network?",
        "ts": "1473107390.000035"
    },
    {
        "type": "message",
        "user": "U0VKPD6A2",
        "text": "<@U1XLE4K5Z> There's not a use case for that yet. Right now they explore complementary architectures.",
        "ts": "1473108371.000036"
    },
    {
        "type": "message",
        "user": "U1ZUSJHAA",
        "text": "<@U0YQQRNU8> Yes, \"a feature for the validator to track invalid transactions for some duration of time so it can return a better status to the client.\" is what I expect. If this is help-wanted, I'd like to work on this.",
        "ts": "1473125545.000037"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "<@U1ZUSJHAA>: that would be great",
        "ts": "1473126531.000038"
    },
    {
        "type": "message",
        "user": "U21HV589Z",
        "text": "Hi there, I understand the Validator Network Launcher is available for running multiple instances of txnvalidator on a single virtual machine, but I'm keen to try and set up multiple VMs instead, so was wondering if someone might be able to provide some quick advice for setting up a validator network using multiple VMs? So far I've configured a private network of vagrant VMs all able to communicate with each other (on separate private-address IPs, separate host ports), but have been a little unsure as to how to configure each one's txnvalidator.js properly (i.e get them to listening to each other over Sawtooth).",
        "ts": "1473127450.000039"
    },
    {
        "type": "message",
        "user": "U21HV589Z",
        "text": "Specifically, what should the \"LedgerURL\" and \"Listen\" entries look like in each machine?  (not sure where should they point :confused: )",
        "ts": "1473127468.000040"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "<@U21HV589Z> - the first node you launch will need to be a special 'genesis' node.  You can set Genesis to true in the config file or provide --genesis command line argument",
        "ts": "1473127862.000041"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "<@U21HV589Z> - LedgerURL can be a list of URLs and can point to all other nodes or some subset.  at a minimum you want the genesis node in that list.",
        "ts": "1473127928.000042"
    },
    {
        "type": "message",
        "user": "U21HV589Z",
        "text": "Ah excellent! Yep that makes sense (completely missed that LedgerURL was a list) - with \"Listen\", should that refer to the node's address itself?",
        "ts": "1473128093.000043"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "For Listen, you want to bind to the ip available to the other nodes.  you need both the gossip and http statements (as in the txnvalidator.js.example).  alternatively, you can bind to 0.0.0.0 (all interfaces) and specify the Endpoint section of the config for each node.  Usually, I'd do Listen unless there is NAT involved.",
        "ts": "1473128121.000044"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "bgattas: note in the config, you actually set LedgerURL: [\"http:\/\/\", \"......\", \"....\"]. so it's actually a list in the json.",
        "ts": "1473128258.000045"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "you will need to also set NodeName to something unique for each validator",
        "ts": "1473128304.000046"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "also, if you want to be able to do any restarting, make sure to pre-generate the node's keys",
        "ts": "1473128363.000047"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "\"KeyFile\" : \"{key_dir}\/{node}.wif\"",
        "ts": "1473128372.000048"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "that file",
        "ts": "1473128374.000049"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "you can use 'sawtooth keygen' to generate it",
        "ts": "1473128390.000050"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "(use -h - the usage is pretty simple)",
        "ts": "1473128404.000051"
    },
    {
        "type": "message",
        "user": "U21HV589Z",
        "text": "Rightio, I'll update the http\/gossip statements to reflect the IP that other nodes can access (that actually makes much more sense now). Thanks so much for those tips on NodeName and keygen too!",
        "ts": "1473128438.000052"
    },
    {
        "type": "message",
        "user": "U0YQQRNU8",
        "text": "great, let us know how it goes!",
        "ts": "1473128513.000053"
    },
    {
        "type": "message",
        "user": "U21HV589Z",
        "text": "\"received connect confirmation\" - looking good! <https:\/\/gyazo.com\/a2d9b592befb22c2ee2415eda7df31cb>",
        "attachments": [
            {
                "service_name": "Gyazo",
                "service_url": "https:\/\/gyazo.com",
                "fallback": "Gyazo Photo: ",
                "image_url": "https:\/\/bot.gyazo.com\/a2d9b592befb22c2ee2415eda7df31cb.png",
                "image_width": 1211,
                "image_height": 94,
                "from_url": "https:\/\/gyazo.com\/a2d9b592befb22c2ee2415eda7df31cb",
                "image_bytes": 21949,
                "title_link": "https:\/\/gyazo.com\/a2d9b592befb22c2ee2415eda7df31cb",
                "service_icon": "https:\/\/gyazo.com\/favicon.ico",
                "id": 1
            }
        ],
        "ts": "1473129158.000054"
    },
    {
        "type": "message",
        "user": "U21HV589Z",
        "text": "thanks again for the help",
        "ts": "1473129163.000056"
    }
]