[
    {
        "type": "message",
        "user": "U1ZUSJHAA",
        "text": "<@U0YQQRNU8> <@U1H7F590E> I updated the PR,  renamed \"public_key\" to \"PublicKey\", and changed tests of LIBOR such that they aren't sensitive, please take a look.\n<https:\/\/github.com\/hyperledger\/sawtooth-core\/pull\/39>",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "Maintain consistent style by feihujiang \u00b7 Pull Request #39 \u00b7 hyperledger\/sawtooth-core \u00b7 GitHub",
                "title_link": "https:\/\/github.com\/hyperledger\/sawtooth-core\/pull\/39",
                "text": "Signed-off-by: feihujiang <mailto:jiangfeihu@huawei.com|jiangfeihu@huawei.com> The style of most of keys in minfo is camel case, I think we'd better maintain consistent style.",
                "fallback": "GitHub: Maintain consistent style by feihujiang \u00b7 Pull Request #39 \u00b7 hyperledger\/sawtooth-core",
                "thumb_url": "https:\/\/avatars2.githubusercontent.com\/u\/2322270?v=3&s=400",
                "from_url": "https:\/\/github.com\/hyperledger\/sawtooth-core\/pull\/39",
                "thumb_width": 400,
                "thumb_height": 400,
                "service_icon": "https:\/\/a.slack-edge.com\/bfaba\/img\/unfurl_icons\/github.png",
                "id": 1
            }
        ],
        "ts": "1481280398.000111"
    },
    {
        "type": "message",
        "user": "U1ZUSJHAA",
        "text": "<@U1V9UML9E> Which PR of mine you can review? Thanks.",
        "ts": "1481281173.000113"
    },
    {
        "type": "message",
        "user": "U1ZUSJHAA",
        "text": "I opened a new PR, Who could take a look? Thanks!",
        "ts": "1481284257.000114"
    },
    {
        "type": "message",
        "user": "U1ZUSJHAA",
        "text": "<https:\/\/github.com\/hyperledger\/sawtooth-core\/pull\/40>",
        "ts": "1481284261.000115"
    },
    {
        "type": "message",
        "user": "U1ZUSJHAA",
        "text": "Usage:\n.\/bin\/run_tests [-m Module]\nOptions:\n-h print usage and exit\n-m Module only run tests of module, &lt;core, validator, mktplace, bond, arcade&gt;",
        "ts": "1481284309.000116"
    },
    {
        "type": "message",
        "user": "U2LH2TFTP",
        "text": "<@U0Y4ZF0QM>  thank you for the pointers.\nsawtooth-core\/tools\/guest-files\/local-env.sh file does have an entry for signing directory export.\nHowever, I can't see anything written into \/etc\/profile. \nDo you mean profile.d when you said profile (my guess is based on bootstrap.d\/14-setup_stl_environment.sh code). If so, I can see local-env.sh inside profile.d, which doesn't have entry for signing directory export. However, it has entries for exporting PYTHONPATH with core,validator etc.,\n\nLooks like I have an old local-env.sh file in \/etc\/profile.d (that matches with git sha1 commit f3c1ed5ae1bbee056e8fcfa8e4fd5675e69556b4). And it is not getting updated during vagrant up (as you expected) for some reason (?).\n\nAnything I might be missing in the vagrant configuration?\n\np.s: As I mentioned in my previous post i could solve the issue by exporting python path.",
        "edited": {
            "user": "U2LH2TFTP",
            "ts": "1481285197.000000"
        },
        "ts": "1481285057.000117"
    },
    {
        "type": "message",
        "user": "U1V9UML9E",
        "text": "<@U1ZUSJHAA> I looked at #39 just a few minutes ago. I could probably look at others. :slightly_smiling_face:",
        "ts": "1481298267.000119"
    },
    {
        "type": "message",
        "user": "U1V9UML9E",
        "text": "<@U1ZUSJHAA>  See my feedback - I see Shawn A. also commented on that.",
        "ts": "1481298282.000120"
    },
    {
        "type": "message",
        "user": "U24M29R4G",
        "text": "I have been trying to start a few validator nodes outside of vagrant environment using ```sawtooth cluster start -m docker --count 4``` . I see that the validators exit immediately after start with exit code 127. Does anyone know as to why this might be happening. The build of all the images go through successfully ```sawtooth docker build --all```",
        "ts": "1481319068.000121"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U24M29R4G|nikileshsa> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/nikileshsa\/F3DN144CX\/docker_validator_exits_outside_with_error_127_.sh|docker validator exits outside with error 127.>",
        "file": {
            "id": "F3DN144CX",
            "created": 1481319124,
            "timestamp": 1481319124,
            "name": "docker_validator_exits_outside_with_error_127_.sh",
            "title": "docker validator exits outside with error 127.",
            "mimetype": "text\/plain",
            "filetype": "shell",
            "pretty_type": "Shell",
            "user": "U24M29R4G",
            "editable": true,
            "size": 2812,
            "mode": "snippet",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F3DN144CX\/docker_validator_exits_outside_with_error_127_.sh?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F3DN144CX\/download\/docker_validator_exits_outside_with_error_127_.sh?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/nikileshsa\/F3DN144CX\/docker_validator_exits_outside_with_error_127_.sh",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F3DN144CX-0a444ebc85",
            "edit_link": "https:\/\/hyperledgerproject.slack.com\/files\/nikileshsa\/F3DN144CX\/docker_validator_exits_outside_with_error_127_.sh\/edit",
            "preview": "chain@chain:~\/projects\/sawtooth-core\/tools$ sudo sawtooth cluster start -m docker --count 4\r\nStarting: validator-000\r\nStarting: validator-001\r\nStarting: validator-002\r\nStarting: validator-003\r",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text\/plain',window.getSelection().toString().replace(\/\\u200b\/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>chain@chain:~\/projects\/sawtooth-core\/tools<span class=\"cm-def\">$ sudo<\/span> sawtooth cluster <span class=\"cm-builtin\">start<\/span> <span class=\"cm-attribute\">-m<\/span> docker <span class=\"cm-attribute\">--count<\/span> <span class=\"cm-number\">4<\/span><\/pre><\/div>\n<div><pre>Starting: validator-000<\/pre><\/div>\n<div><pre>Starting: validator-001<\/pre><\/div>\n<div><pre>Starting: validator-002<\/pre><\/div>\n<div><pre>Starting: validator-003<\/pre><\/div>\n<\/div>\n<\/div>\n",
            "lines": 75,
            "lines_more": 70,
            "preview_is_truncated": true,
            "channels": [
                "C16GB844D"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 0
        },
        "user": "U24M29R4G",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U24M29R4G|nikileshsa>",
        "bot_id": null,
        "ts": "1481319125.000122"
    },
    {
        "type": "message",
        "user": "U1V9UML9E",
        "text": "<@U24M29R4G> It expects that you create a network first and we usually use a known subnet. so 'docker network create -d bridge --subnet 10.200.200.0\/24 sawtooth'",
        "ts": "1481327212.000123"
    },
    {
        "type": "message",
        "user": "U1V9UML9E",
        "text": "<@U24M29R4G> We should document that better!",
        "ts": "1481327240.000124"
    },
    {
        "type": "message",
        "user": "U24M29R4G",
        "text": "hi <@U1V9UML9E>. the validator containers exit even when the sawtooth bridge network exists..",
        "ts": "1481327391.000125"
    },
    {
        "type": "message",
        "user": "U24M29R4G",
        "text": "I had a word with <@U1L6PRGTF> yesterday and he shared the commands to start validators using docker..and it works perfectly inside the vagrant environment. I am just trying to do the same outside vagrant.",
        "ts": "1481327520.000126"
    }
]