[
    {
        "type": "message",
        "user": "U2D13KBQD",
        "text": "<@U1Y2R5C9L>  I run the SDK deploy method, get an error :description=open \/var\/hyperledger\/production\/crypto\/client\/ks\/raw\/eca.cert.chain: no such file or directory",
        "ts": "1478078069.000316"
    },
    {
        "type": "message",
        "user": "U1AU8DRQR",
        "text": "anyone working on <https:\/\/jira.hyperledger.org\/browse\/FAB-907> ?",
        "ts": "1478088804.000317"
    },
    {
        "type": "message",
        "user": "U0YNFB22X",
        "text": "<@U1AU8DRQR> I think member services data folder needs to be cleaned up. ",
        "ts": "1478104454.000318"
    },
    {
        "type": "message",
        "user": "U13Q594J2",
        "text": "<@U0YNFB22X> Where can we find that `member services data folder` ? I remember seeing this issue in the first run ... Incase If you are referring `\/var\/hyperledger\/production` I deleted that re-ran the program too",
        "edited": {
            "user": "U13Q594J2",
            "ts": "1478113663.000000"
        },
        "ts": "1478113630.000319"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "<@U1AU8DRQR> It is a documentation update in the read me file, but until it is updated, you can do the following to get test cases pass:\n1.  remove \/var\/hyperledger\/production (or whatever location you have in core.yaml)\n2. Remove the KeyValStore properties file - tests use test.properties from $user.home\n\nRun the tests now and it should work",
        "ts": "1478131835.000322"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "<@U2D13KBQD> This is not related to SDK, please post in <#C27E2LGJY|fabric-peer-dev>, see <https:\/\/github.com\/hyperledger-archives\/fabric\/issues\/580> for a similar problem",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "peer login fails with TLS failed loading external cert error \u00b7 Issue #580 \u00b7 hyperledger-archives\/fabric \u00b7 GitHub",
                "title_link": "https:\/\/github.com\/hyperledger-archives\/fabric\/issues\/580",
                "text": "Assigning to @jeffgarratt since it looks like a TLS thing. Running obc-peer inside a Docker container. When I do a CLI login, I get back a \"error on client login: open: no such file or directory\" ...",
                "fallback": "GitHub: peer login fails with TLS failed loading external cert error \u00b7 Issue #580 \u00b7 hyperledger-archives\/fabric",
                "thumb_url": "https:\/\/avatars1.githubusercontent.com\/u\/11295979?v=3&s=400",
                "from_url": "https:\/\/github.com\/hyperledger-archives\/fabric\/issues\/580",
                "thumb_width": 400,
                "thumb_height": 400,
                "service_icon": "https:\/\/a.slack-edge.com\/e8ef6\/img\/unfurl_icons\/github.png",
                "id": 1
            }
        ],
        "ts": "1478144073.000323"
    }
]