[
    {
        "type": "message",
        "user": "U2HQUFH6F",
        "text": "Hi, i am writing  chain code application in Golang and want to create a web UI for it. I found out <https:\/\/github.com\/IBM-Blockchain\/cp-web> this example . Here they are using mycreds.json to fetch the information regarding peers, ca, users. \n\nThis file can be auto generated if you are using IBM blue mix. Since I am developing on local development environment in the HyperLedger fabric , i can't get this file directly. Can someone please help me out and guide how to get around this? I want to use the HFC SDK and this credentials file is necessary for it.",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "IBM-Blockchain\/cp-web",
                "title_link": "https:\/\/github.com\/IBM-Blockchain\/cp-web",
                "text": "cp-web - A demonstration of a commercial paper trading application on IBM Blockchain.",
                "fallback": "GitHub: IBM-Blockchain\/cp-web",
                "thumb_url": "https:\/\/avatars2.githubusercontent.com\/u\/17178768?v=3&s=400",
                "from_url": "https:\/\/github.com\/IBM-Blockchain\/cp-web",
                "thumb_width": 200,
                "thumb_height": 200,
                "service_icon": "https:\/\/github.com\/apple-touch-icon.png",
                "id": 1
            }
        ],
        "ts": "1480321523.004383"
    },
    {
        "type": "message",
        "user": "U2L125QGL",
        "text": "hi, i am trying to deploy chaincode in peer as peer chaincode deploy -p <http:\/\/github.com\/hyperledger\/fabric\/examples\/chaincode\/go\/chaincode_example02|github.com\/hyperledger\/fabric\/examples\/chaincode\/go\/chaincode_example02>  -n mycc -c '{\"Args\": [\"init\", \"a\",\"100\", \"b\", \"200\"]}' -----I am getting error:",
        "ts": "1480326970.004385"
    },
    {
        "type": "message",
        "user": "U2L125QGL",
        "text": "09:55:36.019 [msp] func1 -&gt; INFO 001 Creating the msp manager\n09:55:36.019 [msp] GetManager -&gt; INFO 002 Returning MSP manager %!p(msp.peerMspManagerImpl={map[]  false})\n09:55:36.020 [msp] Setup -&gt; INFO 003 Setting up the MSP manager from config file \/opt\/gopath\/src\/github.com\/hyperledger\/fabric\/msp\/peer-config.json\n09:55:36.020 [msp] newBccspMsp -&gt; INFO 004 Creating BCCSP-based MSP instance\n09:55:36.021 [SW_BCCSP] createKeyStoreIfNotExists -&gt; INFO 005 KeyStore path [\/tmp] missing [false]: [&lt;clean&gt;]\n09:55:36.022 [msp] Setup -&gt; INFO 006 Setting up MSP DEFAULT\n09:55:36.022 [msp] Setup -&gt; INFO 007 Setting up MSP instance from file \/opt\/gopath\/src\/github.com\/hyperledger\/fabric\/msp\/peer-config.json\n09:55:36.055 [msp] newIdentity -&gt; INFO 008 Creating identity instance for ID &amp;{{DEFAULT} ROOTCA}\n09:55:36.055 [msp] newSigningIdentity -&gt; INFO 009 Creating signing identity instance for ID &amp;{{DEFAULT} PEER}\n09:55:36.055 [msp] Setup -&gt; INFO 00a MSP manager setup complete (config file \/opt\/gopath\/src\/github.com\/hyperledger\/fabric\/msp\/peer-config.json)\nError: Error endorsing chaincode: rpc error: code = 12 desc = unknown service protos.Endorser",
        "ts": "1480326974.004386"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "hy all i am  facing following error:-vp0_1  | 09:55:22.752 [dockercontroller] deployImage -&gt; ERRO 01d Error building images: dial unix \/var\/run\/docker.sock: connect: no such file or directory\nvp0_1  | 09:55:22.753 [dockercontroller] deployImage -&gt; ERRO 01e Image Output:\nvp0_1  | ********************\nvp0_1  |\nvp0_1  | ********************\nvp0_1  | 09:55:22.757 [dockercontroller] Start -&gt; ERRO 01f start-could not recreate container Post <http:\/\/unix.sock\/containers\/create?name=dev-vp0-ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539>: dial unix \/var\/run\/docker.sock: connect: no such file or directory\nvp0_1  | 09:55:22.757 [chaincode] Launch -&gt; ERRO 020 launchAndWaitForRegister failed Error starting container: Post <http:\/\/unix.sock\/containers\/create?name=dev-vp0-ee5b24a1f17c356dd5f6e37307922e39ddba12e5d2e203ed93401d7d05eb0dd194fb9070549c5dc31eb63f4e654dbd5a1d86cbb30c48e3ab1812590cd0f78539>: dial unix \/var\/run\/docker.sock: connect: no such file or directory",
        "ts": "1480328292.004387"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "<@U1F1CU61Y>  I hope, you have found the docker configuration file in Centos. Does it contain any entry like the following,\nDOCKER_OPTS=\"-s=aufs -r=true --api-cors-header='*' -H <tcp:\/\/0.0.0.0:2375> -H unix:\/\/\/var\/run\/docker.sock \"",
        "edited": {
            "user": "U2KL18VPU",
            "ts": "1480329620.000000"
        },
        "ts": "1480329485.004388"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "this essentially says docker to listen on both TCP\/IP port 2375 and unix socket \/var\/run\/docker.sock",
        "ts": "1480329513.004389"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "yes problem is that docker is not listening",
        "ts": "1480329956.004391"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i did not find any file with the given entry",
        "ts": "1480329970.004392"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "let me try",
        "ts": "1480329973.004393"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "ok",
        "ts": "1480330209.004394"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "In centos, the configuration file seems to be \/etc\/sysconfig\/docker",
        "ts": "1480330502.004395"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U2KL18VPU>  i found the file",
        "ts": "1480330517.004396"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "and edit deployed chaincode",
        "ts": "1480330524.004397"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "but again same problem",
        "ts": "1480330529.004398"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "but this time its listening on 172.17.0.1 2375",
        "ts": "1480330539.004399"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i am able to telnet from host machine but not able to telnet from docker images",
        "ts": "1480330558.004400"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "can you copy paste the DOCKER_OPTS in your docker file?",
        "ts": "1480330576.004401"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "we can see if some typo etc..",
        "ts": "1480330598.004402"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i have edit docker.service file",
        "ts": "1480330652.004403"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "as following",
        "ts": "1480330668.004404"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "ExecStart=\/usr\/bin\/dockerd -H <tcp:\/\/0.0.0.0:2375> -H unix:\/\/\/var\/run\/docker.sock",
        "ts": "1480330669.004405"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i found this somewhere",
        "ts": "1480330703.004406"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "because there is no such configuration file under \/etc\/",
        "ts": "1480330729.004407"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "ok.. can you see whether this is what actually running? (ps ax|grep dockerd) \nThis should show you the command being run",
        "ts": "1480330833.004408"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "yes i have checked it",
        "ts": "1480330848.004409"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "even its listening on 2375 port",
        "ts": "1480330856.004410"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "try whether docker is listening on \/var\/run\/docker.sock also.. (sudo fuser -v \/var\/run\/docker.sock)",
        "ts": "1480331020.004411"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "hmm let me check",
        "ts": "1480331208.004412"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "same problem :disappointed:",
        "ts": "1480331311.004413"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "what is the output of the fuser command?",
        "ts": "1480331329.004414"
    },
    {
        "type": "message",
        "user": "U0PB67X4K",
        "text": "<@U1F1CU61Y>  - are you running the peers as Docker containers as well?",
        "ts": "1480331361.004415"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U2KL18VPU>  can you please specify exact command for fuser ?",
        "ts": "1480331514.004416"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "sudo fuser -v \/var\/run\/docker.sock",
        "ts": "1480331535.004417"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U0PB67X4K>  yes i am running both",
        "ts": "1480331536.004418"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U2KL18VPU> \n\n[root@localhost ~]# sudo fuser -v \/var\/run\/docker.sock\nCannot stat \/var\/run\/docker.sock: No such file or directory\nCannot stat \/var\/run\/docker.sock: No such file or directory",
        "ts": "1480331561.004419"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "can you give the output of \"ps ax|grep dockerd\"",
        "ts": "1480331610.004420"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "I suspect, the docker is not starting with proper options.",
        "ts": "1480331640.004421"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "[root@localhost ~]# ps ax|grep dockerd\n  779 pts\/0    S+     0:00 grep dockerd",
        "ts": "1480331642.004422"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "no docker is running??",
        "ts": "1480331654.004423"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "sorry wait",
        "ts": "1480331668.004424"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i got output from wrong terminal",
        "ts": "1480331679.004425"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "ok",
        "ts": "1480331682.004426"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "[root@localhost ~]# ps ax|grep dockerd\n 9168 ?        Ssl    0:00 \/usr\/bin\/dockerd -H <tcp:\/\/172.30.65.26:2375> -H unix:\/\/\/var\/run\/docker.sock\n 9480 pts\/2    S+     0:00 grep --color=auto dockerd",
        "ts": "1480331703.004427"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "this is the output",
        "ts": "1480331707.004428"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "and following is output of fuser command:-\n\n[root@localhost ~]#  sudo fuser -v \/var\/run\/docker.sock\n                     USER        PID ACCESS COMMAND\n\/run\/docker.sock:    root       9168 F.... dockerd",
        "ts": "1480331734.004429"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "ok..",
        "ts": "1480331755.004430"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "so, it seems docker is actually listening to \/var\/run\/docker.sock properly..",
        "ts": "1480331779.004431"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "yes",
        "ts": "1480331789.004432"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "but not able to telnet to specific port",
        "ts": "1480331824.004433"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i dont know why",
        "ts": "1480331827.004434"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "wait",
        "ts": "1480331835.004435"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "change the docker command to \/usr\/bin\/dockerd -H <tcp:\/\/0.0.0.0:2375> -H unix:\/\/\/var\/run\/docker.sock",
        "ts": "1480331880.004436"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "don't put the IP, instead use 0.0.0.0",
        "ts": "1480331895.004437"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i had tried this also",
        "ts": "1480331904.004438"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "even tried with 127.0.0.1",
        "ts": "1480331912.004439"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "please try with 0.0.0.0 once again and try to telnet",
        "ts": "1480331931.004440"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "okay sure",
        "ts": "1480331949.004441"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "able to telnet from localhost",
        "ts": "1480332056.004442"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "not from other machine",
        "ts": "1480332066.004443"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "its giving following error:-\n\nvp0_1  | 11:21:11.858 [dockercontroller] deployImage -&gt; ERRO 020 Error building images: cannot connect to Docker endpoint",
        "ts": "1480332094.004444"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "do you have any default firewall running?",
        "ts": "1480332102.004445"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "no",
        "ts": "1480332106.004446"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "firewall is off",
        "ts": "1480332115.004447"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "can you check \"iptables -L -n -v\"",
        "ts": "1480332124.004448"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "sudo iptables -L -n -v",
        "ts": "1480332133.004449"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "on the machine where docker is running...",
        "ts": "1480332148.004450"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U1F1CU61Y|ankitkamra> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F38A30T7G\/-.txt|Untitled>",
        "file": {
            "id": "F38A30T7G",
            "created": 1480332275,
            "timestamp": 1480332275,
            "name": "-.txt",
            "title": "Untitled",
            "mimetype": "text\/plain",
            "filetype": "text",
            "pretty_type": "Plain Text",
            "user": "U1F1CU61Y",
            "editable": true,
            "size": 8538,
            "mode": "snippet",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F38A30T7G\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F38A30T7G\/download\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F38A30T7G\/-.txt",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F38A30T7G-ae561ac0fb",
            "edit_link": "https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F38A30T7G\/-.txt\/edit",
            "preview": "3Chain INPUT (policy ACCEPT 0 packets, 0 bytes)\r\n pkts bytes target     prot opt in     out     source               destination         \r\n    0     0 ACCEPT     udp  --  virbr0 *       0.0.0.0\/0            0.0.0.0\/0            udp dpt:53\r\n    0     0 ACCEPT     tcp  --  virbr0 *       0.0.0.0\/0            0.0.0.0\/0            tcp dpt:53\r\n    0     0 ACCEPT     udp  --  virbr0 *       0.0.0.0\/0            0.0.0.0\/0            udp dpt:67\r",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text\/plain',window.getSelection().toString().replace(\/\\u200b\/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>3Chain INPUT (policy ACCEPT 0 packets, 0 bytes)<\/pre><\/div>\n<div><pre> pkts bytes target     prot opt in     out     source               destination         <\/pre><\/div>\n<div><pre>    0     0 ACCEPT     udp  --  virbr0 *       0.0.0.0\/0            0.0.0.0\/0            udp dpt:53<\/pre><\/div>\n<div><pre>    0     0 ACCEPT     tcp  --  virbr0 *       0.0.0.0\/0            0.0.0.0\/0            tcp dpt:53<\/pre><\/div>\n<div><pre>    0     0 ACCEPT     udp  --  virbr0 *       0.0.0.0\/0            0.0.0.0\/0            udp dpt:67<\/pre><\/div>\n<div><pre><\/pre><\/div>\n<\/div>\n<\/div>\n",
            "lines": 128,
            "lines_more": 123,
            "preview_is_truncated": true,
            "channels": [
                "C0Y4PEU22"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 0
        },
        "user": "U1F1CU61Y",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U1F1CU61Y|ankitkamra>",
        "bot_id": null,
        "ts": "1480332276.004451"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "please find output for the same",
        "ts": "1480332289.004452"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "try flushing the INPUT chain.. \nsudo iptables -F INPUT",
        "ts": "1480332465.004453"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "an then try the telnet",
        "ts": "1480332496.004454"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "yes now able to telnet",
        "ts": "1480332518.004455"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "ok..",
        "ts": "1480332531.004456"
    },
    {
        "type": "message",
        "user": "U2AS0GVSP",
        "text": "in v7 I am getting \"transport: http2Server.HandleStreams failed to receive the preface from client: EOF\" followed by what looks to be a peer crash every 4-6 hours. any ideas?",
        "ts": "1480332689.004457"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "v7?",
        "ts": "1480332751.004458"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U2KL18VPU> chaincode deployed but now getting following error:-\n\nvp0_1  | 11:30:12.360 [dockercontroller] deployImage -&gt; ERRO 020 Error building images: Tag latest not found in repository <http:\/\/docker.io\/hyperledger\/fabric-baseimage|docker.io\/hyperledger\/fabric-baseimage>\nvp0_1  | 11:30:12.360 [dockercontroller] deployImage -&gt; ERRO 021 Image Output:\nvp0_1  | ********************\nvp0_1  | Step 1 : FROM hyperledger\/fabric-baseimage\nvp0_1  | Pulling repository <http:\/\/docker.io\/hyperledger\/fabric-baseimage|docker.io\/hyperledger\/fabric-baseimage>\nvp0_1  | \nvp0_1  | ********************",
        "ts": "1480332777.004459"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "are you a time traveler?",
        "ts": "1480332780.004460"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U2KL18VPU> while querying chaincode getting following error:-\n\nvp0_1  | 11:32:11.493 [devops] invokeOrQuery -&gt; INFO 040 Transaction ID: 23220388-c78b-42ed-ae45-655aed057c5c\nvp0_1  | 11:32:11.493 [rest] processChaincodeInvokeOrQuery -&gt; ERRO 041 Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for 04233c6dd8364b9f0749882eb6d1b50992b942aa0a664182946f411ab46802a88574932ccd75f8c75e780036e363d52dd56ccadc2bfde95709fc39148d76f050 - LedgerError - ResourceNotFound: ledger: resource not found)",
        "ts": "1480332808.004461"
    },
    {
        "type": "message",
        "user": "U2AS0GVSP",
        "text": "okay maybe its v6 then :slightly_smiling_face:",
        "ts": "1480332841.004462"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "<@U1F1CU61Y> I think, there is some problem with fabric-baseimage tag (latest) specified in the core.yaml (chaincode section).. May be it should be something like \"$(ARCH)-$(PROJECT_VERSION)\" instead of \"latest\".. not sure..\nDue to that, the chaincode didn't get deployed, and the query fails.",
        "edited": {
            "user": "U2KL18VPU",
            "ts": "1480333280.000000"
        },
        "ts": "1480333228.004463"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U2AS0GVSP|jackkleeman> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/jackkleeman\/F37HSSHB5\/-.txt|Untitled>",
        "file": {
            "id": "F37HSSHB5",
            "created": 1480333240,
            "timestamp": 1480333240,
            "name": "-.txt",
            "title": "Untitled",
            "mimetype": "text\/plain",
            "filetype": "text",
            "pretty_type": "Plain Text",
            "user": "U2AS0GVSP",
            "editable": true,
            "size": 3723,
            "mode": "snippet",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F37HSSHB5\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F37HSSHB5\/download\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/jackkleeman\/F37HSSHB5\/-.txt",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F37HSSHB5-ca6224008c",
            "edit_link": "https:\/\/hyperledgerproject.slack.com\/files\/jackkleeman\/F37HSSHB5\/-.txt\/edit",
            "preview": "Nov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 2016\/11\/28 11:11:49 transport: http2Server.HandleStreams failed to receive the preface from client: EOF\r\nNov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 11:11:49.512 [peer] ProcessTransaction -> DEBU 21deb ProcessTransaction processing transaction txid = 1cdba193-ec33-46bc-aa6c-847deae3b01b\r\nNov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 11:11:49.512 [peer] ProcessTransaction -> DEBU 21dec Verifying transaction signature 1cdba193-ec33-46bc-aa6c-847deae3b01b\r\nNov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 11:11:49.512 [crypto] Debugf -> DEBU 21ded [validator.test_vp0] Tx confdential level [PUBLIC].\r\nNov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 11:11:49.512 [peer] sendTransactionsToLocalEngine -> DEBU 21dee Marshalling transaction CHAINCODE_QUERY to send to local engine\r",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text\/plain',window.getSelection().toString().replace(\/\\u200b\/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>Nov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 2016\/11\/28 11:11:49 transport: http2Server.HandleStreams failed to receive the preface from client: EOF<\/pre><\/div>\n<div><pre>Nov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 11:11:49.512 [peer] ProcessTransaction -&gt; DEBU 21deb ProcessTransaction processing transaction txid = 1cdba193-ec33-46bc-aa6c-847deae3b01b<\/pre><\/div>\n<div><pre>Nov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 11:11:49.512 [peer] ProcessTransaction -&gt; DEBU 21dec Verifying transaction signature 1cdba193-ec33-46bc-aa6c-847deae3b01b<\/pre><\/div>\n<div><pre>Nov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 11:11:49.512 [crypto] Debugf -&gt; DEBU 21ded [validator.test_vp0] Tx confdential level [PUBLIC].<\/pre><\/div>\n<div><pre>Nov 28 11:11:49 ip-172-31-20-217 docker-compose[15410]: vp0_1         | 11:11:49.512 [peer] sendTransactionsToLocalEngine -&gt; DEBU 21dee Marshalling transaction CHAINCODE_QUERY to send to local engine<\/pre><\/div>\n<div><pre><\/pre><\/div>\n<\/div>\n<\/div>\n",
            "lines": 20,
            "lines_more": 15,
            "preview_is_truncated": true,
            "channels": [
                "C0Y4PEU22"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 0,
            "num_stars": 1
        },
        "user": "U2AS0GVSP",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U2AS0GVSP|jackkleeman>",
        "bot_id": null,
        "ts": "1480333241.004464"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "oh <@U2KL18VPU> so what is you suggestion to resolve the problem ?",
        "ts": "1480333308.004466"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "May be, you can edit the core.yaml (of the peer inside docker image) and look for the tag \"latest\". Try to change it as per my previous message.  However, I am not very sure about this.",
        "ts": "1480333529.004467"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "Let us wait for some expert's help..",
        "ts": "1480333553.004468"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U2KL18VPU>  okay thanks",
        "ts": "1480333669.004471"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "welcome..",
        "ts": "1480333741.004472"
    },
    {
        "type": "message",
        "user": "U2KJHTPQT",
        "text": "Is there a place where we can follow the development status of Fabric?",
        "ts": "1480347227.004475"
    },
    {
        "type": "message",
        "user": "U2KJHTPQT",
        "text": "Like a microblog or changelog summary, ...?",
        "ts": "1480347244.004476"
    },
    {
        "user": "U2XF5L2S3",
        "text": "<@U2XF5L2S3|tbltzk> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1480347265.004477"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "so is there someone looking at this spate of gossip\/* UT failures?",
        "ts": "1480350421.004478"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U0ZJZBJLF> don't mean to pick on you, but you are the only contact point I know for gossip",
        "ts": "1480350443.004479"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "I am seeing numerous gossip\/* failures like: <https:\/\/jenkins.hyperledger.org\/job\/fabric-verify-x86_64\/3346\/console>",
        "ts": "1480350455.004480"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "which test is it this time",
        "ts": "1480350456.004481"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "gossip\/comm in this case",
        "ts": "1480350464.004482"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "though I saw some gossip\/state earlier too",
        "ts": "1480350475.004483"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "wow",
        "ts": "1480350484.004484"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "well, \n```\n13:48:31 \u001b[33munit-tests_1  |\u001b[0m --- FAIL: TestParallelSend (0.01s)\n13:48:31 \u001b[33munit-tests_1  |\u001b[0m panic: listen tcp :5611: bind: address already in use [recovered]\n13:48:31 \u001b[33munit-tests_1  |\u001b[0m \tpanic: listen tcp :5611: bind: address already in use\n```\nIs indeed mine but how is it possible? I use different ports in all the test",
        "ts": "1480350532.004485"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "theres a reasonable chance I need to rebase my patches if there were any recent fixes",
        "ts": "1480350540.004486"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "are you running this locally?",
        "ts": "1480350586.004487"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "oh right",
        "ts": "1480350589.004488"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "no",
        "ts": "1480350591.004489"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "no, this was jenkins",
        "ts": "1480350594.004490"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "that's in CI",
        "ts": "1480350596.004491"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "yeah yeah it's the time",
        "ts": "1480350600.004492"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I think somehow that port is taken by some other port",
        "ts": "1480350612.004493"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "this address already in use is impossible... I use different ports in each test in that file",
        "ts": "1480350634.004494"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "question: why not let the tcp stack pick one for you?",
        "edited": {
            "user": "U0KPFAZNF",
            "ts": "1480350702.000000"
        },
        "ts": "1480350672.004495"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "ephemeral ports, i mean",
        "ts": "1480350688.004496"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "because it's \"hard\"- how do I know which ports are open and which are not?",
        "ts": "1480350723.004498"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "you mean why not bind to 0?",
        "ts": "1480350729.004499"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "right",
        "ts": "1480350733.004500"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "heh, it works the other way",
        "ts": "1480350740.004501"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I get the port I need to bind to, from the gossip layer",
        "ts": "1480350747.004502"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "the comm layer is underneath the gossip layer",
        "ts": "1480350766.004503"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "(as an aside - <@U0KPFAZNF> .. when you say \u201cspate\u201d of failures. \u2026 do all have the same issue ? )",
        "ts": "1480350773.004504"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "reason I ask is\u2026 if so something would be funky given @yakov's `Is indeed mine but how is it possible? I use different ports in all the test`",
        "edited": {
            "user": "U0ULK2JPP",
            "ts": "1480350877.000000"
        },
        "ts": "1480350826.004505"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U0ULK2JPP> I just saw rumblings on the other channels with postings about the cobertura reports...which turned out to be a red herring...when I looked at the root cause of the cobertura error, it was a UT failure in gossip\/*",
        "ts": "1480350830.004506"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I have a question- just to make sure: if I have in the same package- A_test.go and B_test.go",
        "ts": "1480350837.004507"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "do they run serially?",
        "ts": "1480350842.004508"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "well, <@U0KPFAZNF>  that was a failure in gossip\/state, not mine :wink:",
        "ts": "1480350864.004510"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U0ZJZBJLF> its not clear",
        "ts": "1480350869.004511"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "and Corwin said he'll take a look at it",
        "ts": "1480350881.004513"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "go does support parallel execution of tests, but when\/where\/if are varialbes",
        "ts": "1480350896.004514"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "if it's not clear it's weird because the comm test never failed on *that* and that code has been there for weeks",
        "ts": "1480350914.004515"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I think the binding is a fluke... if it persists I'll try to investigate",
        "ts": "1480350930.004516"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U0UHG4VP1> has mentioned some unusual circumstances when a CI minion can be shared somehow",
        "ts": "1480350944.004517"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "yeah, that's a big problem",
        "ts": "1480350953.004518"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "for my code",
        "ts": "1480350957.004519"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "perhaps a test was running concurrently <@U0UHG4VP1> ?",
        "ts": "1480350960.004520"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I remember that",
        "ts": "1480350962.004521"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "But we need to take into consideration the probability of the tests to run *concurrently*",
        "ts": "1480350988.004522"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "for example- if that minion runs the chaincode and the gossip at the same time, it's ok, etc. etc.",
        "ts": "1480351004.004523"
    },
    {
        "type": "message",
        "user": "U0UHG4VP1",
        "text": "There should never be concurrent runs ",
        "ts": "1480351061.004524"
    },
    {
        "type": "message",
        "user": "U0UHG4VP1",
        "text": "What I said is there may be serial runs on one minion",
        "ts": "1480351083.004525"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "ah, right...it was a problem with persistent state",
        "ts": "1480351110.004526"
    },
    {
        "type": "message",
        "user": "U0UHG4VP1",
        "text": "The only way I can imagine this happening is if a test hangs and another starts before a recycle ",
        "ts": "1480351119.004527"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "I couldve sworn there was some problem with file locking from two things running or something too",
        "ts": "1480351130.004528"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "but maybe I am not remembering that correctly or had misunderstood",
        "ts": "1480351145.004529"
    },
    {
        "type": "message",
        "user": "U0UHG4VP1",
        "text": "If a test crashes or something you might leave something locked ",
        "ts": "1480351161.004530"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "ah, ok",
        "ts": "1480351168.004531"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "that couldve been it",
        "ts": "1480351171.004532"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "ahhh",
        "ts": "1480351209.004533"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "really?",
        "ts": "1480351221.004534"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "wait how is that possible?",
        "ts": "1480351227.004535"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "if a test crashes the process terminates",
        "ts": "1480351232.004536"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "if the underlying environment were reused...",
        "ts": "1480351681.004537"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "as opposed to starting fresh",
        "ts": "1480351692.004538"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "but when the test fails the process dies and the port binding dies with it",
        "ts": "1480352080.004541"
    },
    {
        "type": "message",
        "user": "U2AS0GVSP",
        "text": "will I run into any problems having an autorestarting systemd service which runs the peer, runs the chaincode, and sends a deploy command?",
        "ts": "1480354972.004542"
    },
    {
        "type": "message",
        "user": "U2AS0GVSP",
        "text": "does anyone have any scripts that they use to handle the full deploy process?",
        "ts": "1480355127.004543"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U2AS0GVSP> what do you mean by \"runs the chaincode\"?  it sounds like you are using a --devmode model?",
        "ts": "1480357532.004544"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "in a production environment, the peer would manage the lifecycle of the chaincode",
        "ts": "1480357557.004545"
    },
    {
        "type": "message",
        "user": "U2AS0GVSP",
        "text": "yes devmode model",
        "ts": "1480357586.004546"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "fwiw, I do have a supervisord script that runs a v0.6 setup in --devmode with chaincode",
        "ts": "1480357594.004547"
    },
    {
        "type": "message",
        "user": "U2AS0GVSP",
        "text": "this is because I dont want to keep track of the chaincode id",
        "ts": "1480357607.004548"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "but this is not a natural thing to do",
        "ts": "1480357607.004549"
    },
    {
        "type": "message",
        "user": "U2AS0GVSP",
        "text": "could you send that my way?",
        "ts": "1480357618.004550"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "sure, hold on",
        "ts": "1480357623.004551"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U0ZJZBJLF> heres one in gossip\/gossip: <https:\/\/jenkins.hyperledger.org\/job\/fabric-verify-x86_64\/3348\/console>",
        "ts": "1480370645.004552"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "I assume that is different from gossip\/state or gossip\/comms",
        "ts": "1480370659.004553"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "Yep, it's the pull test that failed. I'll take a look tomorrow and see if I can figure out why that happened. It's kinda hard though, even from having stack traces of all goroutines there",
        "edited": {
            "user": "U0ZJZBJLF",
            "ts": "1480371263.000000"
        },
        "ts": "1480371207.004554"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "never seen it fail in CI before however",
        "ts": "1480371217.004555"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "This is weird though, it \"sounds\" like a block went missing, which doesn't make sense because the msgStore size is way higher than the amount of blocks I send in the test. The pull algorithm is supposed to have more than enough time to complete the blocks :confused:",
        "edited": {
            "user": "U0ZJZBJLF",
            "ts": "1480371735.000000"
        },
        "ts": "1480371619.004557"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U10LM0FFZ> ping",
        "ts": "1480372587.004561"
    },
    {
        "type": "message",
        "user": "U10LM0FFZ",
        "text": "<@U2KL18VPU> <@U1F1CU61Y> - the concepts surrounding hyperledger\/fabric-baseimage are being supplanted by hyperledger\/fabric-ccenv.  As such, try pointing to this ccenv image in your docker-compose .yaml.  Another option is to manually pull the baseimage for your platform and then execute a rename to tag it as baseimage:latest",
        "ts": "1480373124.004562",
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "U1F1CU61Y",
                    "U2KL18VPU"
                ],
                "count": 2
            }
        ]
    },
    {
        "type": "message",
        "user": "U10LM0FFZ",
        "text": "This documentation will be updated shortly, but we can work around it in the meantime",
        "ts": "1480373153.004563"
    },
    {
        "type": "message",
        "user": "U10LM0FFZ",
        "text": "for example, ```docker tag hyperledger\/fabric-baseimage:x-86x86_64-0.2.1 hyperledger\/fabric-baseimage:latest```",
        "ts": "1480373311.004564"
    },
    {
        "user": "U365KFA2Y",
        "text": "<@U365KFA2Y|rixon> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1480387517.004565"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U10LM0FFZ> Thank you :slightly_smiling_face: , i have one question that where is fabric-baseimage is running, according to documentation we need to pull only fabric-membersrvc and fabric-peer image. And i have already tagged it with latest.",
        "ts": "1480389310.004566"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U1F1CU61Y> baseimage is used, as the name implies, as the baseimage of most docker images in the system...in v0.6 it is also used directly to compile chaincode",
        "ts": "1480391388.004567"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "in v1.0\/master, there is a new image named \"ccenv\" which takes its place as the environment that we compile chaincode into",
        "ts": "1480391415.004568"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "but the concept is the same, just the name changes",
        "ts": "1480391424.004569"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "the main problem you are seeing is the system is still not yet really equiped to run from anything but from a locally build source environment",
        "ts": "1480391455.004570"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "yes, you can run from docker with a little massaging, but its still not turnkey",
        "ts": "1480391469.004571"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "we are working on that",
        "ts": "1480391471.004572"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U0KPFAZNF> so should i pull fabric-baseimage too ?",
        "ts": "1480391552.004573"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "and fabric-baseimage is used by peer only or as well it must exist on membersrvc machine too ?",
        "ts": "1480391591.004574"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "once see what are all the images you have.. (docker images)",
        "ts": "1480391599.004575"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "it may be just a matter of tagging properly",
        "ts": "1480391624.004576"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "i have two machines, one contains membersrvc image and another contain peer image",
        "ts": "1480391631.004577"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U1F1CU61Y> yes, for v0.6.1-preview, you want to pull hyperledger\/fabric-baseimage:$(arch)-0.0.11",
        "ts": "1480391683.004578"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "and retag it as latest",
        "ts": "1480391689.004579"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "it does not need to exist on the membersrvc node",
        "ts": "1480391705.004580"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "just the peer",
        "ts": "1480391706.004581"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "actually, i think v0.6 only supports x86_64 now that I think of it",
        "ts": "1480391760.004582"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "okay let me try",
        "ts": "1480391792.004583",
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "U2KL18VPU"
                ],
                "count": 1
            }
        ]
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U0KPFAZNF> and <@U2KL18VPU> Thanks a lot, i am trying with provided solution, if i face any problem i will get back to you guys",
        "ts": "1480391844.004584"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U1F1CU61Y> pay attention to the version....v0.6.1-preview uses v0.0.11...the latest is v0.2.1",
        "ts": "1480391909.004585"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "but dont be tempted to use the latest",
        "ts": "1480391915.004586"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "that is not qualified to work together",
        "ts": "1480391928.004587"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "okay thanks",
        "ts": "1480391941.004588"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "np, and good luck",
        "ts": "1480391961.004589",
        "reactions": [
            {
                "name": "slightly_smiling_face",
                "users": [
                    "U1F1CU61Y"
                ],
                "count": 1
            }
        ]
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U0KPFAZNF> and <@U2KL18VPU> i have pulled hyperledger\/fabric-baseimage:hyperledger\/fabric-baseimage and tagged it with hyperledger\/fabric-baseimage:latest but now i am facing following issue:-",
        "ts": "1480394211.004592"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U1F1CU61Y|ankitkamra> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F38NJ32MC\/-.txt|Untitled> and commented: Any inputs ?",
        "file": {
            "id": "F38NJ32MC",
            "created": 1480394232,
            "timestamp": 1480394232,
            "name": "-.txt",
            "title": "Untitled",
            "mimetype": "text\/plain",
            "filetype": "text",
            "pretty_type": "Plain Text",
            "user": "U1F1CU61Y",
            "editable": true,
            "size": 506,
            "mode": "snippet",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F38NJ32MC\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F38NJ32MC\/download\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F38NJ32MC\/-.txt",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F38NJ32MC-53e5104576",
            "edit_link": "https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F38NJ32MC\/-.txt\/edit",
            "preview": "vp0_1  | 04:34:36.685 [dockercontroller] deployImage -> ERRO 01e Error building images: cannot normalise nothing\r\nvp0_1  | 04:34:36.686 [dockercontroller] deployImage -> ERRO 01f Image Output:\r\nvp0_1  | ********************\r\nvp0_1  | Step 1 : FROM hyperledger\/fabric-baseimage\r\nvp0_1  |  ---> 90d869298cb6\r",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text\/plain',window.getSelection().toString().replace(\/\\u200b\/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>vp0_1  | 04:34:36.685 [dockercontroller] deployImage -&gt; ERRO 01e Error building images: cannot normalise nothing<\/pre><\/div>\n<div><pre>vp0_1  | 04:34:36.686 [dockercontroller] deployImage -&gt; ERRO 01f Image Output:<\/pre><\/div>\n<div><pre>vp0_1  | ********************<\/pre><\/div>\n<div><pre>vp0_1  | Step 1 : FROM hyperledger\/fabric-baseimage<\/pre><\/div>\n<div><pre>vp0_1  |  ---&gt; 90d869298cb6<\/pre><\/div>\n<div><pre><\/pre><\/div>\n<\/div>\n<\/div>\n",
            "lines": 11,
            "lines_more": 6,
            "preview_is_truncated": false,
            "channels": [
                "C0Y4PEU22"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 1,
            "initial_comment": {
                "id": "Fc37B9SZ5W",
                "created": 1480394232,
                "timestamp": 1480394232,
                "user": "U1F1CU61Y",
                "is_intro": true,
                "comment": "Any inputs ?",
                "channel": ""
            }
        },
        "user": "U1F1CU61Y",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U1F1CU61Y|ankitkamra>",
        "bot_id": null,
        "ts": "1480394232.004593"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "I've never seen that before",
        "ts": "1480394274.004594"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "ohh",
        "ts": "1480394325.004595"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "Me too :disappointed:",
        "ts": "1480394326.004596"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "Try a quick search on google which may give some hint..",
        "ts": "1480394354.004597"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U1F1CU61Y|ankitkamra> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F382PBSRY\/-.txt|Untitled> and commented: Full error details are here",
        "file": {
            "id": "F382PBSRY",
            "created": 1480394360,
            "timestamp": 1480394360,
            "name": "-.txt",
            "title": "Untitled",
            "mimetype": "text\/plain",
            "filetype": "text",
            "pretty_type": "Plain Text",
            "user": "U1F1CU61Y",
            "editable": true,
            "size": 1128,
            "mode": "snippet",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F382PBSRY\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F382PBSRY\/download\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F382PBSRY\/-.txt",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F382PBSRY-8625aaa6aa",
            "edit_link": "https:\/\/hyperledgerproject.slack.com\/files\/ankitkamra\/F382PBSRY\/-.txt\/edit",
            "preview": "vp0_1  | 04:34:36.685 [dockercontroller] deployImage -> ERRO 01e Error building images: cannot normalise nothing\r\nvp0_1  | 04:34:36.686 [dockercontroller] deployImage -> ERRO 01f Image Output:\r\nvp0_1  | ********************\r\nvp0_1  | Step 1 : FROM hyperledger\/fabric-baseimage\r\nvp0_1  |  ---> 90d869298cb6\r",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text\/plain',window.getSelection().toString().replace(\/\\u200b\/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>vp0_1  | 04:34:36.685 [dockercontroller] deployImage -&gt; ERRO 01e Error building images: cannot normalise nothing<\/pre><\/div>\n<div><pre>vp0_1  | 04:34:36.686 [dockercontroller] deployImage -&gt; ERRO 01f Image Output:<\/pre><\/div>\n<div><pre>vp0_1  | ********************<\/pre><\/div>\n<div><pre>vp0_1  | Step 1 : FROM hyperledger\/fabric-baseimage<\/pre><\/div>\n<div><pre>vp0_1  |  ---&gt; 90d869298cb6<\/pre><\/div>\n<div><pre><\/pre><\/div>\n<\/div>\n<\/div>\n",
            "lines": 25,
            "lines_more": 20,
            "preview_is_truncated": true,
            "channels": [
                "C0Y4PEU22"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 1,
            "initial_comment": {
                "id": "Fc38NJF7C6",
                "created": 1480394360,
                "timestamp": 1480394360,
                "user": "U1F1CU61Y",
                "is_intro": true,
                "comment": "Full error details are here",
                "channel": ""
            }
        },
        "user": "U1F1CU61Y",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U1F1CU61Y|ankitkamra>",
        "bot_id": null,
        "ts": "1480394360.004598"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "yeah doing that too",
        "ts": "1480394375.004599"
    },
    {
        "type": "message",
        "user": "U2L125QGL",
        "text": "Hi, I deploy a chaincode in peer, I am getting error as: Error: Error endorsing chaincode: rpc error: code = 12 desc = unknown service protos.Endorser",
        "ts": "1480395326.004600"
    },
    {
        "type": "message",
        "user": "U2L125QGL",
        "text": "how to solve this?",
        "ts": "1480395334.004601"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U0KPFAZNF> and <@U2KL18VPU> its working with baseimage version x86_64-0.2.1 \nThanks a lot for your support guys",
        "ts": "1480398922.004602",
        "reactions": [
            {
                "name": "grinning",
                "users": [
                    "U2KL18VPU"
                ],
                "count": 1
            }
        ]
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "How did you resolve your last error \"Cannot normalise nothing\"?",
        "ts": "1480398998.004603"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "<@U1F1CU61Y> That information will be helpful for others..",
        "edited": {
            "user": "U2KL18VPU",
            "ts": "1480399059.000000"
        },
        "ts": "1480399019.004604"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U2KL18VPU>  i was using baseimage v0.0.11. I think that was not compatible with peer v0.6.1-preview. I just pulled out another versions and it is working fine with baseimage v0.2.1",
        "ts": "1480399952.004606"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "<@U1F1CU61Y> Thanks for the information..",
        "ts": "1480400047.004607",
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "U1F1CU61Y"
                ],
                "count": 1
            }
        ]
    },
    {
        "user": "U37BX5KQ8",
        "text": "<@U37BX5KQ8|smiley> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1480401315.004608"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "Hi, I start peer as peer node start,  I got an error as below",
        "ts": "1480401426.004609"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U37BX5KQ8|smiley> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/smiley\/F38P5PY94\/-.txt|Untitled>",
        "file": {
            "id": "F38P5PY94",
            "created": 1480401437,
            "timestamp": 1480401437,
            "name": "-.txt",
            "title": "Untitled",
            "mimetype": "text\/plain",
            "filetype": "text",
            "pretty_type": "Plain Text",
            "user": "U37BX5KQ8",
            "editable": true,
            "size": 880,
            "mode": "snippet",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F38P5PY94\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F38P5PY94\/download\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/smiley\/F38P5PY94\/-.txt",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F38P5PY94-470822de0c",
            "edit_link": "https:\/\/hyperledgerproject.slack.com\/files\/smiley\/F38P5PY94\/-.txt\/edit",
            "preview": "06:32:16.379 [committer] NewDeliverService -> INFO 064 Creating committer for single noops endorser\r\n2016\/11\/29 06:32:17 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = \"transport: dial tcp 0.0.0.0:7050: getsockopt: connection refused\"; Reconnecting to {\"0.0.0.0:7050\" <nil>}\r\n2016\/11\/29 06:32:19 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = \"transport: dial tcp 0.0.0.0:7050: getsockopt: connection refused\"; Reconnecting to {\"0.0.0.0:7050\" <nil>}\r\n06:32:19.381 [committer] NewDeliverService -> ERRO 065 Cannot dial to 0.0.0.0:7050, because of grpc: timed out when dialing\r\n2016\/11\/29 06:32:19 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = \"transport: dial tcp 0.0.0.0:7050: getsockopt: connection refused\"; Reconnecting to {\"0.0.0.0:7050\" <nil>}\r",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text\/plain',window.getSelection().toString().replace(\/\\u200b\/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>06:32:16.379 [committer] NewDeliverService -&gt; INFO 064 Creating committer for single noops endorser<\/pre><\/div>\n<div><pre>2016\/11\/29 06:32:17 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = &quot;transport: dial tcp 0.0.0.0:7050: getsockopt: connection refused&quot;; Reconnecting to {&quot;0.0.0.0:7050&quot; &lt;nil&gt;}<\/pre><\/div>\n<div><pre>2016\/11\/29 06:32:19 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = &quot;transport: dial tcp 0.0.0.0:7050: getsockopt: connection refused&quot;; Reconnecting to {&quot;0.0.0.0:7050&quot; &lt;nil&gt;}<\/pre><\/div>\n<div><pre>06:32:19.381 [committer] NewDeliverService -&gt; ERRO 065 Cannot dial to 0.0.0.0:7050, because of grpc: timed out when dialing<\/pre><\/div>\n<div><pre>2016\/11\/29 06:32:19 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = &quot;transport: dial tcp 0.0.0.0:7050: getsockopt: connection refused&quot;; Reconnecting to {&quot;0.0.0.0:7050&quot; &lt;nil&gt;}<\/pre><\/div>\n<div><pre><\/pre><\/div>\n<\/div>\n<\/div>\n",
            "lines": 6,
            "lines_more": 1,
            "preview_is_truncated": false,
            "channels": [
                "C0Y4PEU22"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 0
        },
        "user": "U37BX5KQ8",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U37BX5KQ8|smiley>",
        "bot_id": null,
        "ts": "1480401437.004610"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "please help me out",
        "ts": "1480401450.004611"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U37BX5KQ8> what you are trying to do ? I mean running single peer or two peers from different host",
        "ts": "1480401741.004612"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "<@U1F1CU61Y> two peers with different host",
        "ts": "1480401821.004613"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "so your root peer is running properly??",
        "ts": "1480401874.004614"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "try to do ping and telnet from another host",
        "ts": "1480401888.004615"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "and firewall must be off on both machines",
        "ts": "1480401899.004616"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "yes root peer is running properly and able to ping and telnet",
        "ts": "1480402453.004617"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "firewall is off only in both machines",
        "ts": "1480402465.004618"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U37BX5KQ8>  run following command:-\n\niptables -F\n\non both peers",
        "ts": "1480402644.004619"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "and can you please post your docker-compose files ?",
        "ts": "1480402771.004620"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "k",
        "ts": "1480402819.004621"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U37BX5KQ8|smiley> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/smiley\/F383FKJF4\/-.txt|Untitled>",
        "file": {
            "id": "F383FKJF4",
            "created": 1480403012,
            "timestamp": 1480403012,
            "name": "-.txt",
            "title": "Untitled",
            "mimetype": "text\/plain",
            "filetype": "text",
            "pretty_type": "Plain Text",
            "user": "U37BX5KQ8",
            "editable": true,
            "size": 1049,
            "mode": "snippet",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F383FKJF4\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F383FKJF4\/download\/-.txt?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/smiley\/F383FKJF4\/-.txt",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F383FKJF4-3d96ff2877",
            "edit_link": "https:\/\/hyperledgerproject.slack.com\/files\/smiley\/F383FKJF4\/-.txt\/edit",
            "preview": "vp0:\r\nimage: hyperledger\/fabric-peer:x86_64-0.6.1-preview\r\nports:\r\n - \"7050:7050\"\r\n - \"7051:7051\"\r",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text\/plain',window.getSelection().toString().replace(\/\\u200b\/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>vp0:<\/pre><\/div>\n<div><pre>image: hyperledger\/fabric-peer:x86_64-0.6.1-preview<\/pre><\/div>\n<div><pre>ports:<\/pre><\/div>\n<div><pre> - &quot;7050:7050&quot;<\/pre><\/div>\n<div><pre> - &quot;7051:7051&quot;<\/pre><\/div>\n<div><pre><\/pre><\/div>\n<\/div>\n<\/div>\n",
            "lines": 36,
            "lines_more": 31,
            "preview_is_truncated": true,
            "channels": [
                "C0Y4PEU22"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 0
        },
        "user": "U37BX5KQ8",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U37BX5KQ8|smiley>",
        "bot_id": null,
        "ts": "1480403012.004622"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "please run following command on both peers:- \n\ndocker images\n\nand post the output",
        "ts": "1480403358.004623"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "are your using vagrant ?",
        "ts": "1480403372.004624"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "yes vagrant",
        "ts": "1480403870.004625"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "so have you done port forwarding in Vagrantfile ?",
        "ts": "1480404442.004626"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "yes",
        "ts": "1480405441.004627"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "now peers got connected its working fine",
        "ts": "1480405469.004628"
    },
    {
        "type": "message",
        "user": "U37BX5KQ8",
        "text": "<@U1F1CU61Y> thanq",
        "ts": "1480405483.004629"
    }
]