[
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "Hi all, i am getting following error:-\n\nvp0_1  | 14:05:19.194 [peer] ensureConnected -&gt; WARN 018 Touch service indicates dropped connections, attempting to reconnect...",
        "ts": "1480581016.004731"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "can anyone tell me what can be the possible solution",
        "ts": "1480581028.004732"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "?",
        "ts": "1480581029.004733"
    },
    {
        "type": "message",
        "user": "U22RH7VGT",
        "text": "<@U1F1CU61Y>  i think its not an error your node might have been connected to some peers which might be down now so it is trying to reconnect with those peers",
        "ts": "1480583018.004734"
    },
    {
        "type": "message",
        "user": "U1F1CU61Y",
        "text": "<@U22RH7VGT> okay let me check",
        "ts": "1480583053.004735"
    },
    {
        "user": "U27B19YJH",
        "text": "<@U27B19YJH|tprafull> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1480586329.004736"
    },
    {
        "user": "U39D3065S",
        "text": "<@U39D3065S|ephan> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1480602923.004739"
    },
    {
        "user": "U39DK9LJH",
        "text": "<@U39DK9LJH|amarpreet> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1480603527.004740"
    },
    {
        "type": "message",
        "user": "U36RKMPBQ",
        "text": "Gents, I receive this error message while trying to deploy chaincode from Node.js (HFC SDK):",
        "ts": "1480606939.004741"
    },
    {
        "type": "message",
        "user": "U36RKMPBQ",
        "text": "Debugger listening on [::]:5858\n**** starting HFC sample ****\nmember services address =10.43.185.247:7054\npeer address =10.43.185.247:7051\nDEPLOY_MODE=dev\nenrolling user admin ...\ndeploying chaincode; please wait ...\nEnrolled berci successfully\nFailed to deploy chaincode: request={\"chaincodeName\":\"chaincode_example02\",\"fcn\":\"init\",\"args\":[\"a\",\"100\",\"b\",\"200\"],\"chaincodePath\":\"<http:\/\/github.com\/hyperledger\/fabric\/examples\/chaincode\/go\/chaincode_example02|github.com\/hyperledger\/fabric\/examples\/chaincode\/go\/chaincode_example02>\"}, error=%k EventTransactionError {\nerror:\n{ status: 'FAILURE',\nmsg: &lt;Buffer 43 65 72 74 69 66 69 63 61 74 65 20 68 61 73 20 6e 6f 74 20 62 65 65 6e 20 73 69 67 6e 65 64 20 62 79 20 61 20 74 72 75 73 74 65 64 20 61 75 74 68 6f ... &gt; },\nmsg: 'Certificate has not been signed by a trusted authority. [x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"eca\")]' }\nConnection attempt 1 to node process on 127.0.0.1:5858 failed. Will try again in 500.",
        "ts": "1480606941.004742"
    },
    {
        "type": "message",
        "user": "U36RKMPBQ",
        "text": "Is there anyone who could help me with this?",
        "ts": "1480606967.004743"
    },
    {
        "type": "message",
        "user": "U0PB67X4K",
        "text": "<@U36RKMPBQ>  - you might want to post this over in one of the fabric-sdk-node channels, but a quick guess would be that perhaps the certificates being used by your peer are different than the ones received by the Node client.  This might have happened in you've wiped out \/ restarted membership services, the peer and the client all at different times.   Are you running the peer(s) and membersrvc via Docker?",
        "ts": "1480608862.004744"
    },
    {
        "type": "message",
        "user": "U36RKMPBQ",
        "text": "hi, thanks for feedback. Peer &amp; Membersrvc is running via Docker indeed ... the thing is I am able to interact correctly from my local workstation via the REST APIs (using Postman), but when running Node.JS SDK in Atom I get this problem",
        "ts": "1480609035.004745"
    },
    {
        "type": "message",
        "user": "U0PB67X4K",
        "text": "yeah - via REST the peer you connect to acts as the client so it would make sense that would work",
        "ts": "1480609138.004748"
    },
    {
        "type": "message",
        "user": "U0PB67X4K",
        "text": "what OS are you using?",
        "ts": "1480609159.004749"
    },
    {
        "type": "message",
        "user": "U36RKMPBQ",
        "text": "Windows 7 locally",
        "ts": "1480609196.004750"
    },
    {
        "type": "message",
        "user": "U36RKMPBQ",
        "text": "Dockers running in ec2 AWS cloud",
        "ts": "1480609208.004751"
    },
    {
        "type": "message",
        "user": "U36RKMPBQ",
        "text": "Linux ip-10-43-185-247 4.4.23-31.54.amzn1.x86_64 #1 SMP Tue Oct 18 22:02:09 UTC 2016 x86_64 x86_64 x86_64 GNU\/Linux",
        "ts": "1480609239.004752"
    },
    {
        "type": "message",
        "user": "U36RKMPBQ",
        "text": "Log on the Peer side: vp0_1  | 16:45:11.509 [peer] ProcessTransaction -&gt; ERRO 1de618 ProcessTransaction failed to verify transaction Certificate has not been signed by a trusted authority. [x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"eca\")]",
        "ts": "1480610761.004753"
    },
    {
        "type": "message",
        "user": "U196R0LA2",
        "text": "Are there any other useful docs that outline the changes coming in v1.0? Currently I\u2019m looking at:\n\n* <https:\/\/github.com\/hyperledger\/fabric\/blob\/master\/docs\/abstract_v1.md>\n* <https:\/\/jira.hyperledger.org\/secure\/attachment\/10056\/FabricNext-Community.pdf>\n* <https:\/\/github.com\/hyperledger\/fabric\/tree\/master\/proposals\/r1>",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "hyperledger\/fabric",
                "title_link": "https:\/\/github.com\/hyperledger\/fabric\/blob\/master\/docs\/abstract_v1.md",
                "text": "Read-only mirror of <https:\/\/gerrit.hyperledger.org\/r\/#\/admin\/projects\/fabric>",
                "fallback": "GitHub: hyperledger\/fabric",
                "thumb_url": "https:\/\/avatars3.githubusercontent.com\/u\/7657900?v=3&s=400",
                "from_url": "https:\/\/github.com\/hyperledger\/fabric\/blob\/master\/docs\/abstract_v1.md",
                "thumb_width": 142,
                "thumb_height": 142,
                "service_icon": "https:\/\/github.com\/apple-touch-icon.png",
                "id": 1
            }
        ],
        "edited": {
            "user": "U196R0LA2",
            "ts": "1480616633.000000"
        },
        "ts": "1480615996.004754"
    },
    {
        "type": "message",
        "user": "U2NDE1ZCK",
        "text": "Here is a list that has been posted in the past, <https:\/\/wiki.hyperledger.org\/community\/fabric-design-docs>",
        "ts": "1480617467.004757",
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "U196R0LA2"
                ],
                "count": 1
            }
        ]
    },
    {
        "user": "U147FES4F",
        "text": "<@U147FES4F|shashankbk> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1480630674.004760"
    },
    {
        "type": "message",
        "user": "U2URL5G8P",
        "text": "please anybody guide me what is the use of the Node SDK  ,if a user can hit the chaincode api directly",
        "ts": "1480663059.004765"
    },
    {
        "type": "message",
        "user": "U2URL5G8P",
        "text": "how do i make a dynamic entry in the  memmbersrvc.yml for certificates of the user",
        "ts": "1480663287.004766"
    }
]