[
    {
        "type": "message",
        "user": "U10PB8HPH",
        "text": "Question.  I'm getting a panic because my config file doesn't have a variable peer.discovery.touchPeriod.  What is the correct fix.  Put in a default or abort with a better error message?",
        "ts": "1466937260.000736"
    },
    {
        "type": "message",
        "user": "U10PB8HPH",
        "text": "It's in line 522 of peer.go",
        "ts": "1466937272.000737"
    },
    {
        "type": "message",
        "user": "U0XQ35CDD",
        "text": "Look into the default value in the repo and use that maybe. IIRC it is 6 seconds.",
        "ts": "1466938942.000738"
    },
    {
        "type": "message",
        "user": "U1JK24HE3",
        "text": "Anyone know how to resolve the \"Error: sql: no rows in result set\u201d error from the node SDK?\n```\nhlc already enrolled +12ms\nregistered and enrolled.. making deploy request\n  hlc Member.deploy +2ms\n  hlc TransactionContext.deploy +0ms\n  hlc Received deploy request: {\"chaincodeName\":\"mycc\",\"fcn\":\"init\",\"args\":[\u201c100\u201d,\"200\u201d,\"1\"]} +0ms\n  hlc [TransactionContext] No TCert cached. Retrieving one. +0ms\n  hlc Member.getNextTCert: key=null +0ms\n  hlc Member.getNextTCert: key=null, creating new getter +0ms\n  hlc shouldGetTCerts: yes, we have no tcerts +1ms\n  hlc Failed getting a new TCert [Error: sql: no rows in result set] +70ms\nerror on invoke: {\"error\":{\"code\":2,\"metadata\":{\"_internal_repr\":{}}},\"msg\":\"Error: sql: no rows in result set\u201d}\n```",
        "ts": "1466998239.000739"
    },
    {
        "type": "message",
        "user": "U1JK24HE3",
        "text": "(the deploy works from inside vagrant using the cli)\n```\n.\/peer chaincode deploy -n mycc -c '{\"Function\":\"init\", \"Args\": [\u201c100\u201d,\u201d200\u201d,\u201d1\" ]}\u2019```",
        "edited": {
            "user": "U1JK24HE3",
            "ts": "1466998569.000000"
        },
        "ts": "1466998505.000740"
    },
    {
        "type": "message",
        "user": "U1JK24HE3",
        "text": "All i can find in the issues is a request to add it to the Troubleshooting guide <https:\/\/github.com\/hyperledger\/fabric\/issues\/1835#issuecomment-226236301>",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "Documentation created for the node sdk \u00b7 Issue #1835 \u00b7 hyperledger\/fabric \u00b7 GitHub",
                "title_link": "https:\/\/github.com\/hyperledger\/fabric\/issues\/1835#issuecomment-226236301",
                "text": "The documentation needs cleaning up. Do not have to display it locally file:\/\/\/home\/barry\/src\/github.com\/hyperledger\/fabric\/sdk\/node\/doc\/globals.html The three high globals - hlc, crypto, stats. ...",
                "fallback": "GitHub: Documentation created for the node sdk \u00b7 Issue #1835 \u00b7 hyperledger\/fabric",
                "thumb_url": "https:\/\/avatars2.githubusercontent.com\/u\/18034452?v=3&s=400",
                "from_url": "https:\/\/github.com\/hyperledger\/fabric\/issues\/1835#issuecomment-226236301",
                "thumb_width": 420,
                "thumb_height": 420,
                "service_icon": "https:\/\/a.slack-edge.com\/e8ef6\/img\/unfurl_icons\/github.png",
                "id": 1
            }
        ],
        "ts": "1466998753.000742"
    }
]