[
    {
        "user": "U2GG5LADV",
        "text": "<@U2GG5LADV|wangmzdl> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484124519.001542"
    },
    {
        "type": "message",
        "user": "U3ENCLLUA",
        "text": "<@U3LH9V41L> <@U3E300R6Z> ask ask for help on <#C3J4X2DJL|help> channel",
        "ts": "1484129075.001543"
    },
    {
        "type": "message",
        "user": "U1V5VNSAD",
        "text": "Hi, For hyperledger 0.6 version other than MAC OS and windows any other OS are supported. Is Ubuntu supported?",
        "ts": "1484129888.001544"
    },
    {
        "type": "message",
        "user": "U12452RAP",
        "text": "Should cross platform",
        "ts": "1484129990.001545"
    },
    {
        "type": "message",
        "user": "U1W210996",
        "text": "there are images for different platforms. you can use it to start via Docker on your system",
        "ts": "1484130003.001546"
    },
    {
        "type": "message",
        "user": "U12452RAP",
        "text": "just a standard go program ",
        "ts": "1484130016.001547"
    },
    {
        "type": "message",
        "user": "U294FECPQ",
        "text": "Hi all. Can anybody explain how ecert expiration works in fabric 0.6? I am assuming that once the membership service is created, the expiration date is set for some time (3 months?) after it starts",
        "ts": "1484132496.001548"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "Hi. I tried running an infinite loop in a invoke function. I noticed that the transactions was unsuccessful. How is the fabric handling the memory\/RAM utilization of peers? Below  is the snippet of  code I tried.  \nfunc (t *SimpleChaincode) Invoke(stub shim.ChaincodeStubInterface, function string, args []string) ([]byte, error) {\n\nfor {\n\t\tfmt.Println(\"empty\")\n\t}\nreturn nil,nil\n}",
        "edited": {
            "user": "U12AHQ3NK",
            "ts": "1484134957.000000"
        },
        "ts": "1484134757.001549"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "<@U12AHQ3NK> currently the invoke will just timeout",
        "ts": "1484139486.001551"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "<@U1ZT4H8MC> thanks..",
        "edited": {
            "user": "U12AHQ3NK",
            "ts": "1484139927.000000"
        },
        "ts": "1484139881.001554"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "<@U0ULK2JPP>  wat is the approx timeout period?",
        "ts": "1484146215.001558"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "currently 30 secs I think",
        "ts": "1484146340.001559"
    },
    {
        "type": "message",
        "user": "U3H68QR7X",
        "text": "<@U12AHQ3NK> I saw you had used Credits in the Issues repo. Do you have any idea why their provided examples would fail?",
        "ts": "1484146423.001560"
    },
    {
        "type": "message",
        "user": "U195M30MD",
        "text": "is it possible to browse the history of a given chaincode state?",
        "ts": "1484146463.001561"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "<@U0ULK2JPP> ok..",
        "ts": "1484146593.001562"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "<@U3H68QR7X>: actually in the documentation they had provided incorrect information to run the example which caused them to fail",
        "ts": "1484146638.001563"
    },
    {
        "type": "message",
        "user": "U3H68QR7X",
        "text": "<@U12AHQ3NK> thanks, do you know if there is correct information available?",
        "ts": "1484146667.001564"
    },
    {
        "type": "message",
        "user": "U3H68QR7X",
        "text": "or where I'd need to look?",
        "ts": "1484146674.001565"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "<@U3H68QR7X> I wil check if I have them or else u can contact the developer itself.",
        "ts": "1484146810.001566"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "<@U0ULK2JPP> ..Is C-C to interaction possible when privacy turned on in v0.6?",
        "ts": "1484146851.001567"
    },
    {
        "user": "U3PBR406M",
        "text": "<@U3PBR406M|bur> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484146878.001568"
    },
    {
        "type": "message",
        "user": "U2URL5G8P",
        "text": "<@U3E300R6Z>  you can get it from car-lease-demo\\Documentation\\API methods and car-lease-demo\\Documentation\\Chaincode interface",
        "ts": "1484153111.001569"
    },
    {
        "type": "message",
        "user": "U2URL5G8P",
        "text": "or you can see the app.js where all the api routing is written",
        "ts": "1484153174.001570"
    },
    {
        "type": "message",
        "user": "U2URL5G8P",
        "text": "or you can directly see the chaincode in the chaincode folder in which no. of functions definition are listed you can read it from their",
        "ts": "1484153264.001571"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "<@U12AHQ3NK> C-C interaction is not possible with privacy on in v0.6. That said, note that the security model is different in 1.0 so better to have a migration plan. The approach I\u2019d take is to not rely upon privacy being turned on in 0.6. For more info do check with fabric-crypto",
        "edited": {
            "user": "U0ULK2JPP",
            "ts": "1484153779.000000"
        },
        "ts": "1484153738.001572"
    },
    {
        "type": "message",
        "user": "U3NCSU999",
        "text": "any suggestions on how to run the cp-web demo using a local network created from IBM-Blockchain\/fabric-images? I encounter the \"Identity or token does not match\" error when I used \"enrollId\": \"WebAppAdmin\" and \"enrollSecret\": \"DJY27pEnl16d\" in the mycreds.json configuration file. I posted the same question but with more details of my attempts in GitHub (<https:\/\/github.com\/IBM-Blockchain\/cp-web\/issues\/67>), but haven't gotten a response yet. So, I'm wondering if anyone here would know",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "Failed to run demo using local network, Error: failed to enroll registrar: Identity or token does not match \u00b7 Issue #67 \u00b7 IBM-Blockchain\/cp-web \u00b7 GitHub",
                "title_link": "https:\/\/github.com\/IBM-Blockchain\/cp-web\/issues\/67",
                "text": "I set up a network with 4 peers and a CA as described here (<https:\/\/github.com\/IBM-Blockchain\/cp-web\/blob\/master\/docs\/use_local_hyperledger.md>). I verified that the network is running by checking a...",
                "fallback": "GitHub: Failed to run demo using local network, Error: failed to enroll registrar: Identity or token does not match \u00b7 Issue #67 \u00b7 IBM-Blockchain\/cp-web",
                "thumb_url": "https:\/\/avatars0.githubusercontent.com\/u\/20483211?v=3&s=400",
                "from_url": "https:\/\/github.com\/IBM-Blockchain\/cp-web\/issues\/67",
                "thumb_width": 420,
                "thumb_height": 420,
                "service_icon": "https:\/\/a.slack-edge.com\/bfaba\/img\/unfurl_icons\/github.png",
                "id": 1
            }
        ],
        "ts": "1484154082.001574"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "<@U0ULK2JPP> thanks",
        "ts": "1484190504.001579"
    },
    {
        "type": "message",
        "user": "U12AHQ3NK",
        "text": "<@U0ULK2JPP>  In v1.0 how is the  security model different from v0.6 ? \n",
        "ts": "1484191144.001580"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U3P28G5M3|weihu> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/weihu\/F3PQQR589\/pasted_image_at_2017_01_12_02_06_pm.png|Pasted image at 2017-01-12, 2:06 PM> and commented: hello, when i run command `make dist-clean all`, I got error:",
        "file": {
            "id": "F3PQQR589",
            "created": 1484201183,
            "timestamp": 1484201183,
            "name": "Pasted image at 2017_01_12 02_06 PM.png",
            "title": "Pasted image at 2017-01-12, 2:06 PM",
            "mimetype": "image\/png",
            "filetype": "png",
            "pretty_type": "PNG",
            "user": "U3P28G5M3",
            "editable": false,
            "size": 63044,
            "mode": "hosted",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F3PQQR589\/pasted_image_at_2017_01_12_02_06_pm.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F3PQQR589\/download\/pasted_image_at_2017_01_12_02_06_pm.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_64": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F3PQQR589-2c4159e721\/pasted_image_at_2017_01_12_02_06_pm_64.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_80": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F3PQQR589-2c4159e721\/pasted_image_at_2017_01_12_02_06_pm_80.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_360": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F3PQQR589-2c4159e721\/pasted_image_at_2017_01_12_02_06_pm_360.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_360_w": 360,
            "thumb_360_h": 87,
            "thumb_480": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F3PQQR589-2c4159e721\/pasted_image_at_2017_01_12_02_06_pm_480.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_480_w": 480,
            "thumb_480_h": 116,
            "thumb_160": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F3PQQR589-2c4159e721\/pasted_image_at_2017_01_12_02_06_pm_160.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_720": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F3PQQR589-2c4159e721\/pasted_image_at_2017_01_12_02_06_pm_720.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_720_w": 720,
            "thumb_720_h": 174,
            "image_exif_rotation": 1,
            "original_w": 937,
            "original_h": 226,
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/weihu\/F3PQQR589\/pasted_image_at_2017_01_12_02_06_pm.png",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F3PQQR589-852b3e8625",
            "channels": [
                "C0Y4PEU22"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 1,
            "initial_comment": {
                "id": "Fc3PPWQ7G8",
                "created": 1484201183,
                "timestamp": 1484201183,
                "user": "U3P28G5M3",
                "is_intro": true,
                "comment": "hello, when i run command `make dist-clean all`, I got error:",
                "channel": ""
            }
        },
        "user": "U3P28G5M3",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U3P28G5M3|weihu>",
        "bot_id": null,
        "ts": "1484201185.001581"
    },
    {
        "type": "message",
        "user": "U3P28G5M3",
        "text": "can anyone help me?",
        "ts": "1484201199.001582"
    }
]