[
    {
        "user": "U3VLWE86T",
        "text": "<@U3VLWE86T|hannes> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485163844.002525"
    },
    {
        "type": "message",
        "user": "U3UBGFRQD",
        "text": "hi! are there any preview sources of `1.0` to try?",
        "ts": "1485166526.002526"
    },
    {
        "type": "message",
        "user": "U0Z6DQ030",
        "text": "Hi, using either of the following images, *hyperledger\/fabric-peer:x86_64-0.6.1-preview*, or *ibmblockchain\/fabric-peer:x86_64-0.6.1-preview*, I get the following error when I attempt to deploy chaincode, *11:26:44.521 [chaincode] Launch -&gt; ERRO 058 launchAndWaitForRegister failed Error starting container: cannot normalise nothing*. The message appears on all (5) the peers",
        "ts": "1485171599.002528"
    },
    {
        "user": "U3BJSFP9R",
        "text": "<@U3BJSFP9R|kirkwall> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485172228.002529"
    },
    {
        "user": "U3VP447U7",
        "text": "<@U3VP447U7|gatakka> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485175612.002530"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "<@U3SCKQB4P> here is my docker-compose file",
        "ts": "1485176264.002531"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "membersrvc:\n   image: hyperledger\/fabric-membersrvc\n   ports:\n     - \"7054:7054\"\n   command: membersrvc\nvp0:\n   image: hyperledger\/fabric-peer\n   ports:\n     - \"7050:7050\"\n     - \"7051:7051\"\n     - \"7053:7053\"\n   environment:\n     - CORE_PEER_ADDRESSAUTODETECT=true\n     - CORE_VM_ENDPOINT=unix:\/\/\/var\/run\/docker.sock\n     - CORE_LOGGING_LEVEL=DEBUG\n     - CORE_PEER_ID=vp0\n     - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054\n     - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054\n     - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054\n     - CORE_SECURITY_ENABLED=true\n     - CORE_SECURITY_ENROLLID=mytest_vp0\n     - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT\n   links:\n     - membersrvc\n   command: sh -c \"sleep 20; peer node start --peer-chaincodedev\"",
        "ts": "1485176265.002532"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "for a single peer node",
        "ts": "1485176274.002533"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "<@U34TJFSCB> I think it should be test_vp0 in CORE_SECURITY_ENROLLID",
        "ts": "1485176491.002534"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "hey guys im having a problem using hfc sdk as an interface between my app and chaincode. im using hyperledger v0.6. The thing is, that I am unable to get errors with `invokeTx.on('error', function(results) {....})`",
        "ts": "1485176546.002535"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "where `var invokeTx = userObj.invoke(invokeRequest)`",
        "ts": "1485176580.002536"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "this only happens when using invoke. in the case of query everything works perfekt",
        "ts": "1485176600.002537"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "on error is never triggered in invokes",
        "ts": "1485176642.002538"
    },
    {
        "user": "U3V5A5E20",
        "inviter": "U294TV8R3",
        "text": "<@U3V5A5E20|caroline.church> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485176669.002539"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "<@U3S1PENVA> Thanks, however, that does not resolve the problem",
        "ts": "1485176684.002540"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "you still have \u201cidentity lookup error\u201d?",
        "ts": "1485176745.002541"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "the funny thing is that i get the error in the log of the peer node but it is not caught by invokeTx.on('error', ....)",
        "ts": "1485176784.002542"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "is there anything known about this issue?",
        "ts": "1485181006.002543"
    },
    {
        "type": "message",
        "user": "U3GBDEXG8",
        "text": "Got a question about TCerts  ... how are child PreKeys distributed to auditors? Can anyone walk me through  the flow?",
        "ts": "1485185335.002544"
    },
    {
        "user": "U3V5J478A",
        "text": "<@U3V5J478A|tomthebuzz> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485186953.002545"
    },
    {
        "type": "message",
        "user": "U25ATRAMB",
        "text": "What are some possible causes for a chaincode error like:\n`Chaincode handler FSM cannot handle message (RANGE_QUERY_STATE) with payload size (18) while in state: ready`?\nThis is on the 0.6.1-preview peer in the hyperledger\/fabric-peer docker image, using --peer-chaincodedev",
        "ts": "1485188814.002548"
    },
    {
        "type": "message",
        "user": "U25ATRAMB",
        "text": "the deploy transaction seemed to work just fine, as do most invoke transactions; it's just the queries that fail",
        "ts": "1485188852.002549"
    },
    {
        "type": "message",
        "user": "U0YJUECE8",
        "text": "<@U25ATRAMB> this *could* be your problem:  I've seen this where people are trying to use the v0.6 branch of the code and then are following the instructions in the v0.6 branch of the documentation, but....get twisted up because there are a couple spots in this doc where it has a wget (for the chaincode) and a git clone (for getting the fabric code available locally in order to build the chaincode) that refer to *master*.   The problem is, that *master* is now v1.0 code.    So, they are running Docker images with v0.6 code but when they build the chaincode locally, it incorporates v1.0 code in into it.   The solution is, in the *wget* and the *git clone*,  change *master* to *v0.6* in the path name.   I am being purposely vague as to where this documentation is, because if I've guessed correctly, you know what I'm referring to, but if I've guessed wrong, it's something else and I don't want to lead you on a wild goose chase.   I hope this helps.",
        "ts": "1485189102.002550"
    },
    {
        "type": "message",
        "user": "U25ATRAMB",
        "text": "silliman: thanks",
        "ts": "1485189565.002551"
    },
    {
        "type": "message",
        "user": "U0YJUECE8",
        "text": "<@U25ATRAMB> yw, there's a decent chance that this is what you've run up against.",
        "ts": "1485189716.002552"
    },
    {
        "type": "message",
        "user": "U25ATRAMB",
        "text": "are there any documents on migration from v0.6 to v1.0?",
        "ts": "1485190011.002553"
    },
    {
        "type": "message",
        "user": "U0YJUECE8",
        "text": "<@U25ATRAMB> Not that I'm aware of ...   chaincode is expected to be able to migrate with minimal changes, but the underlying architecture of the fabric is quite different and so migration of the state data is not supported IIRC ...  there are some demo apps that folks are working on migrating from 0.6 to 1.0 (e.g. car-lease-demo at <https:\/\/github.com\/IBM-Blockchain\/car-lease-demo>) so it's possible that someone may at some point produce a document on how to migrate chaincode from v0.6 to v1.0",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "IBM-Blockchain\/car-lease-demo",
                "title_link": "https:\/\/github.com\/IBM-Blockchain\/car-lease-demo",
                "text": "car-lease-demo - A demonstration using IBM Blockchain to show how the lifecycle of vehicles can be recorded on a blockchain",
                "fallback": "GitHub: IBM-Blockchain\/car-lease-demo",
                "thumb_url": "https:\/\/avatars2.githubusercontent.com\/u\/17178768?v=3&s=400",
                "from_url": "https:\/\/github.com\/IBM-Blockchain\/car-lease-demo",
                "thumb_width": 200,
                "thumb_height": 200,
                "service_icon": "https:\/\/github.com\/apple-touch-icon.png",
                "id": 1
            }
        ],
        "ts": "1485190684.002554"
    },
    {
        "user": "U2785CB1N",
        "text": "<@U2785CB1N|det> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485192233.002556"
    },
    {
        "user": "U3V990ESH",
        "text": "<@U3V990ESH|fmarino> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485193696.002557"
    },
    {
        "type": "message",
        "user": "U3V990ESH",
        "text": "Hello everyone! I'm just trying make a docker-compose up to 4 peers with pbft consensus, but they're not communicating with each others, the error on VP logs is: chatWithPeer -&gt; ERRO 030 Error creating connection to peer address vp0:7051: grpc: timed out when dialing \n\nOn vp0 is: grpc: Server.Serve failed to create ServerTransport:  connection error: desc = \"transport: write tcp 172.18.0.4:7051-&gt;172.18.0.6:48898: write: connection reset by peer\"\n\nCan someone help me with this issue?",
        "ts": "1485194155.002558"
    },
    {
        "type": "message",
        "user": "U3UPNQL3E",
        "text": "<https:\/\/hyperledger-fabric.readthedocs.io\/en\/v0.6\/Setup\/Chaincode-setup\/#running-the-cli-or-rest-api>\n&gt; To log in through the REST API, send a POST request to the \/registrar endpoint, containing the  enrollmentID and enrollmentPW listed in the eca.users section of the membersrvc.yaml file.\nthe link to membersrvc.yaml is broken, where can i find it?",
        "edited": {
            "user": "U3UPNQL3E",
            "ts": "1485201654.000000"
        },
        "ts": "1485201563.002559"
    },
    {
        "type": "message",
        "user": "U39DK9LJH",
        "text": "can someone explain to me the difference between a bank and institution re: membersrvc.yaml?",
        "ts": "1485201583.002560"
    },
    {
        "type": "message",
        "user": "U3UPNQL3E",
        "text": "amarpreet where did you find membersrvc.yaml?",
        "ts": "1485201621.002561"
    },
    {
        "type": "message",
        "user": "U39DK9LJH",
        "text": "on the membersrvc",
        "ts": "1485201639.002562"
    },
    {
        "type": "message",
        "user": "U39DK9LJH",
        "text": "i am building it via docker",
        "ts": "1485201649.002563"
    },
    {
        "type": "message",
        "user": "U3UPNQL3E",
        "text": "somewhere in here? <https:\/\/hub.docker.com\/r\/hyperledger\/fabric-membersrvc\/>",
        "ts": "1485201699.002565"
    },
    {
        "type": "message",
        "user": "U39DK9LJH",
        "text": "er... bcq: <https:\/\/raw.githubusercontent.com\/hyperledger-archives\/fabric\/master\/membersrvc\/membersrvc.yaml>",
        "ts": "1485201812.002566"
    },
    {
        "type": "message",
        "user": "U3UPNQL3E",
        "text": "hm. it's an archived file that isn't in the latest version of <http:\/\/github.com\/hyperledger\/fabric|github.com\/hyperledger\/fabric>",
        "ts": "1485202018.002567"
    },
    {
        "type": "message",
        "user": "U3AECURPZ",
        "text": "<@U3BSMKS21> I think the different behaviour is caused by the fact that the invoke operation is async and query synch.",
        "ts": "1485203419.002571"
    },
    {
        "type": "message",
        "user": "U39DK9LJH",
        "text": "is there currently (0.6) no redundancy in terms of the membersrvc?",
        "ts": "1485203709.002572"
    },
    {
        "type": "message",
        "user": "U3UPNQL3E",
        "text": "how do you use this? <https:\/\/hyperledger-fabric.readthedocs.io\/en\/v0.6\/API\/MemberServicesAPI\/>\nis this somehow available in one of the sdks?",
        "ts": "1485203948.002575"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U3V990ESH> master?",
        "ts": "1485204439.002576"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "there is a known issue affecting docker containers on master atm: <https:\/\/jira.hyperledger.org\/browse\/FAB-1652>",
        "ts": "1485204516.002577"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "it sounds like you might be impacted",
        "ts": "1485204521.002578"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "I have this patched locally, would be willing to share but its not super easy to incorporate",
        "ts": "1485204542.002579"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "hopefully, will get the fixes merged in the next few days",
        "ts": "1485204556.002580"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "PM me if you are desperate, I can walk you though the local patching",
        "ts": "1485204570.002581"
    },
    {
        "user": "U344ZJT9P",
        "text": "<@U344ZJT9P|drteck> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485205025.002582"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U0ULK2JPP>: do you know if anyone uses the TLS features between chaincode container and peer?",
        "ts": "1485215364.002583"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "I'm in that code, and unless I am missing something, I suspect it is broken",
        "ts": "1485215390.002584"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "And thus I am guessing it's not used",
        "ts": "1485215428.002585"
    },
    {
        "user": "U3VDLN47L",
        "text": "<@U3VDLN47L|chen.nie> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485218100.002586"
    },
    {
        "type": "message",
        "user": "U0YJUECE8",
        "text": "<@U3UPNQL3E> membersrvcs from v0.6 is replaced by fabric-ca in v1.0, that's why you wouldn't see it in the latest verion of <http:\/\/github.com\/hyperledger\/fabric|github.com\/hyperledger\/fabric> which is v1.0",
        "ts": "1485225707.002587"
    },
    {
        "type": "message",
        "user": "U0YJUECE8",
        "text": "<@U39DK9LJH> AFAIK you're correct, there is no redundancy for membersrvc in 0.6, but don't worry, v1.0 membersrvc is replaced by fabric-ca and the design does allow for redundancy.",
        "ts": "1485225871.002588"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "<@U3S1PENVA> Yes, I am.  I suspecting that there is a mismatch between my fabric-peer fabric-membersrvc images and the version in my $GOPATH\/src\/github.com\/hyperledger\/fabric.",
        "ts": "1485228547.002589"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "I'm not sure if this is the case, but that is all that I can think of.",
        "ts": "1485228565.002590"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "Is the v1.0 version (or the latest on master) for the hyperledger\/fabric and docker images stable enough to use?",
        "ts": "1485228607.002591"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "I'm unable to now even getting the Fabric Starter Kit to run using the instructions on <http:\/\/hyperledger-fabric.readthedocs.io\/en\/v0.6\/starter\/fabric-starter-kit\/>",
        "ts": "1485228750.002592"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "My peer node container always fails to start",
        "ts": "1485229121.002593"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "I've made sure that I started with a clean slate ensuring I have no docker containers running and removed all of my fabric images.  I am following the instructions for the Fabric Starter Kit step by step but my peer node container fails to start.  I still get the following errors:",
        "ts": "1485230084.002594"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "peer          | 03:53:27.897 [crypto] Debug -&gt; DEBU 01f [validator.vp]  TLS disabled...\npeer          | 03:53:27.898 [crypto] Debug -&gt; DEBU 020 [validator.vp]  Getting ECA client...done\npeer          | 03:53:27.899 [crypto] Errorf -&gt; ERRO 021 [validator.vp] Failed requesting read certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\npeer          | 03:53:27.899 [crypto] Errorf -&gt; ERRO 022 [validator.vp] Failed requesting ECA certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\npeer          | 03:53:27.899 [crypto] Errorf -&gt; ERRO 023 [validator.vp] Failed getting ECA certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\npeer          | 03:53:27.899 [crypto] Errorf -&gt; ERRO 024 [validator.vp] Failed retrieving ECA certs chain [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\npeer          | 03:53:27.899 [crypto] Errorf -&gt; ERRO 025 [validator.vp] Failed registering node crypto engine [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\npeer          | 03:53:27.899 [crypto] Errorf -&gt; ERRO 026 [validator.vp] Failed registering peer [vp]: [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure]\npeer          | 03:53:27.899 [crypto] Errorf -&gt; ERRO 027 [validator.vp] Failed registering [vp]: [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure]\npeer          | 03:53:27.899 [crypto] RegisterValidator -&gt; ERRO 028 Failed registering validator [vp] with name [vp] [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\npeer          | Error: rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure",
        "ts": "1485230085.002595"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "The instructions in the Fabric Starter Kit is pulling the fabric-starter-kit, fabric-membersrvc, and fabric-peer images from latest.  Can anyone help to determine if this is a problem with the actual images or is there something else in the setup on my local machine that I am missing or need to do?",
        "ts": "1485230419.002596"
    },
    {
        "user": "U1WTH9EQ5",
        "text": "<@U1WTH9EQ5|sonyeric> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1485234787.002597"
    },
    {
        "type": "message",
        "user": "U11CP8FF1",
        "text": "Docker has been upgraded to v1.13. Should we use this release ?  (Ubuntu upgrade automatically upgrade to v1.13.x).",
        "ts": "1485235919.002598"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "Hello, is it possible to hide (part of the) transaction details from some of the validating peers (in Fabric v0.6)? Eg., when competitors are running peer nodes in a blockchain setup, they may not be willing to reveal all the data to every other node. Whether, Fabric is suitable for such usecases?",
        "ts": "1485235945.002599"
    },
    {
        "type": "message",
        "user": "U11CP8FF1",
        "text": "<@U2KL18VPU>  Probably, the right answer is separate business network while using the same infrastructures.  competitor may join to network (say BizA), but can not join to (say BizB). If a company want to hide the data, all transaction goes to BizB network.",
        "ts": "1485238794.002602"
    },
    {
        "type": "message",
        "user": "U2KL18VPU",
        "text": "<@U11CP8FF1> Ok. So, by \"separate business network\", do you mean running multiple instances of blockchain (BizA, BizB) on the same infrastructure, and some companies are registered on BizA and some on BizB?",
        "edited": {
            "user": "U2KL18VPU",
            "ts": "1485241218.000000"
        },
        "ts": "1485240057.002603"
    }
]