[
    {
        "type": "message",
        "user": "U25ATRAMB",
        "text": "hey all; I'm running into a bug that may or may not be chaintool related. I can run and deploy my chaincode, and run all of the invoke transactions, but any time I do a query I get this error: \n```Error handling message: [dd955c2b-f4e6-4d34-9aa1-febe2926d542]Chaincode handler FSM cannot handle message (RANGE_QUERY_STATE) with payload size (36) while in state: ready```",
        "ts": "1484779802.000068"
    },
    {
        "type": "message",
        "user": "U25ATRAMB",
        "text": "This is old code that I had written last summer and am now trying to get working again, so it's quite possible that it has to do with changes in the new fabric stuff",
        "ts": "1484779869.000069"
    },
    {
        "user": "U3U4Y046B",
        "text": "<@U3U4Y046B|gammavega> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484787062.000070"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U25ATRAMB> it sounds like its unrelated, but sometimes failures of incongruence can be misleading",
        "ts": "1484793310.000071"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "can you tell me about your environment?",
        "ts": "1484793322.000072"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "e.g. what version of fabric, what version of chaintool, etc ?",
        "ts": "1484793332.000073"
    }
]